<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Análise de Regressão Logística Multinomial</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="analise_regressao_multinomial_files/libs/clipboard/clipboard.min.js"></script>
<script src="analise_regressao_multinomial_files/libs/quarto-html/quarto.js"></script>
<script src="analise_regressao_multinomial_files/libs/quarto-html/popper.min.js"></script>
<script src="analise_regressao_multinomial_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="analise_regressao_multinomial_files/libs/quarto-html/anchor.min.js"></script>
<link href="analise_regressao_multinomial_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="analise_regressao_multinomial_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="analise_regressao_multinomial_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="analise_regressao_multinomial_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="analise_regressao_multinomial_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Análise de Regressão Logística Multinomial</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="carregar-bibliotecas-necessárias" class="level2">
<h2 class="anchored" data-anchor-id="carregar-bibliotecas-necessárias">Carregar bibliotecas necessárias</h2>
</section>
<section id="análise-1" class="level1">
<h1>ANÁLISE 1</h1>
<p>Análise com todas as variáveis do banco sem nenhuma combinação.</p>
<section id="carregando-os-dados" class="level2">
<h2 class="anchored" data-anchor-id="carregando-os-dados">1.Carregando os dados</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"det_transicao.csv"</span>, <span class="at">sep =</span> <span class="st">";"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="do">## Selecionando variáveis</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>variaveis <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Transition"</span>, <span class="st">"temp_med"</span>, <span class="st">"umid_med"</span>, <span class="st">"precip_tot"</span>,</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>               <span class="st">"thr_temp"</span>, <span class="st">"thr_umid"</span>, <span class="st">"thr_prec"</span>, <span class="st">"thr_temp_umid"</span>, </span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>               <span class="st">"tipo_regiao"</span>,<span class="st">"altitude"</span>,<span class="st">"bioma"</span>, <span class="st">"koppen"</span>, <span class="st">"pop22"</span>,</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>               <span class="st">"prop_esgot"</span>, <span class="st">"prop_residuo"</span>)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data[, variaveis]</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Identificar e remover colunas completamente vazias ou com alta quantidade de NA</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> <span class="fu">select_if</span>(<span class="sc">~</span> <span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(.)) <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="do">## nenhuma foi</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Converter variáveis numéricas com vírgula decimal e categorizar as variáveis de texto</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>    <span class="fu">across</span>(<span class="fu">where</span>(<span class="sc">~</span> <span class="fu">all</span>(<span class="fu">grepl</span>(<span class="st">"^[0-9,.]+$"</span>, .))), <span class="sc">~</span> <span class="fu">as.numeric</span>(<span class="fu">gsub</span>(<span class="st">","</span>, <span class="st">"."</span>, .))),</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>    <span class="fu">across</span>(<span class="fu">where</span>(is.character), as.factor))</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Visão geral dos dados</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 5,570
Columns: 15
$ Transition    &lt;fct&gt; Piorou, Se manteve, Se manteve, Se manteve, Se manteve, …
$ temp_med      &lt;dbl&gt; 25.5, 26.1, 25.3, 25.8, 25.4, 25.1, 25.2, 26.0, 25.7, 26…
$ umid_med      &lt;dbl&gt; 75.7, 78.1, 75.9, 76.7, 75.7, 75.6, 76.2, 79.3, 76.8, 80…
$ precip_tot    &lt;dbl&gt; 591.3, 625.5, 479.8, 639.2, 505.2, 542.1, 545.8, 572.2, …
$ thr_temp      &lt;dbl&gt; 361.0, 365.0, 356.7, 363.0, 357.0, 357.0, 358.0, 359.3, …
$ thr_umid      &lt;dbl&gt; 307.7, 324.7, 319.7, 319.7, 317.3, 312.7, 317.0, 350.3, …
$ thr_prec      &lt;dbl&gt; 5.0, 5.0, 3.0, 6.3, 4.0, 5.0, 4.0, 4.3, 4.0, 5.0, 7.0, 7…
$ thr_temp_umid &lt;dbl&gt; 305.3, 324.0, 314.0, 317.7, 311.7, 307.7, 312.3, 345.3, …
$ tipo_regiao   &lt;fct&gt; nao metropolitana, nao metropolitana, nao metropolitana,…
$ altitude      &lt;dbl&gt; 246.08, 165.90, 224.18, 229.95, 192.22, 359.62, 266.89, …
$ bioma         &lt;fct&gt; amazonia, amazonia, amazonia, amazonia, amazonia, amazon…
$ koppen        &lt;fct&gt; Am, Am, Am, Am, Am, Am, Am, Am, Am, Am, Am, Am, Am, Am, …
$ pop22         &lt;dbl&gt; 21558, 100896, 5107, 92202, 15237, 15747, 7503, 12633, 2…
$ prop_esgot    &lt;dbl&gt; 2.24, 8.91, 21.01, 54.03, 16.73, 5.17, 11.55, 7.91, 13.7…
$ prop_residuo  &lt;dbl&gt; 56.86, 85.14, 49.77, 78.94, 78.35, 69.11, 37.83, 55.74, …</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Transition      temp_med        umid_med       precip_tot    
 Melhorou  : 759   Min.   :14.30   Min.   :57.20   Min.   : 108.3  
 Piorou    :1163   1st Qu.:20.73   1st Qu.:66.90   1st Qu.: 309.9  
 Se manteve:3648   Median :23.50   Median :73.10   Median : 403.1  
                   Mean   :23.22   Mean   :72.71   Mean   : 410.4  
                   3rd Qu.:25.90   3rd Qu.:78.30   3rd Qu.: 501.2  
                   Max.   :28.60   Max.   :87.80   Max.   :1332.1  
                                                                   
    thr_temp        thr_umid        thr_prec      thr_temp_umid  
 Min.   : 13.0   Min.   :133.7   Min.   : 0.000   Min.   : 13.0  
 1st Qu.:225.8   1st Qu.:256.7   1st Qu.: 2.700   1st Qu.:184.8  
 Median :335.0   Median :325.0   Median : 4.700   Median :216.7  
 Mean   :294.3   Mean   :305.9   Mean   : 5.277   Mean   :238.9  
 3rd Qu.:366.3   3rd Qu.:361.3   3rd Qu.: 7.300   3rd Qu.:316.7  
 Max.   :366.3   Max.   :366.3   Max.   :26.700   Max.   :366.3  
                                                                 
            tipo_regiao      altitude                  bioma     
 metropolitana    : 445   Min.   :   1.67   amazonia      : 503  
 nao metropolitana:5125   1st Qu.: 222.60   caatinga      :1096  
                          Median : 427.60   cerrado       :1063  
                          Mean   : 451.24   mata atlantica:2739  
                          3rd Qu.: 650.83   pampa         : 160  
                          Max.   :1601.42   pantanal      :   9  
                                                                 
     koppen         pop22            prop_esgot      prop_residuo   
 Aw     :1337   Min.   :     836   Min.   :  0.00   Min.   :  0.00  
 Cfa    :1138   1st Qu.:    5282   1st Qu.: 12.80   1st Qu.: 54.31  
 As     : 892   Median :   11096   Median : 38.02   Median : 74.06  
 BSh    : 420   Mean   :   37298   Mean   : 42.25   Mean   : 70.19  
 Cwa    : 407   3rd Qu.:   24615   3rd Qu.: 70.43   3rd Qu.: 89.22  
 Cfb    : 405   Max.   :12200180   Max.   :100.00   Max.   :100.00  
 (Other): 971                                                       </code></pre>
</div>
</div>
</section>
<section id="verificação-dos-pressupostos" class="level2">
<h2 class="anchored" data-anchor-id="verificação-dos-pressupostos">2. Verificação dos pressupostos</h2>
<section id="multicolinearidade" class="level3">
<h3 class="anchored" data-anchor-id="multicolinearidade">2.1 Multicolinearidade</h3>
<ol type="1">
<li><strong>Cálculo do VIF (Variance Inflation Factor):</strong> O VIF foi calculado para cada variável preditora no modelo. Isso foi feito após a remoção de colinearidade redundante e tratamento das variáveis para garantir que todas estejam no formato correto (numérico ou categórico).</li>
<li><strong>Variável dependente:</strong> Transition foi temporariamente convertida para numérica apenas para calcular o VIF. Esse ajuste é feito para facilitar a análise de multicolinearidade.</li>
<li><strong>Detecção e remoção de colinearidade:</strong> Usamos o <em>findLinearCombos</em> para remover variáveis redundantes, evitando o problema de “aliasing” no modelo, o que ocorre quando variáveis altamente correlacionadas criam dependência linear.</li>
</ol>
<p><strong><em>Intrepretação:</em></strong></p>
<ul>
<li><p><strong>Valores de VIF &lt; 5:</strong> São considerados aceitáveis, indicando baixa multicolinearidade. Nas variáveis como altitude, pop22, prop_esgot, e prop_residuo têm VIFs baixos, sugerindo pouca ou nenhuma colinearidade problemática com outras variáveis.</p></li>
<li><p><strong>Valores de VIF entre 5 e 10:</strong> Indicariam alguma multicolinearidade, mas ainda podem ser aceitáveis dependendo do contexto. No entanto, nenhuma variável nesse modelo tem VIF entre 5 e 10.</p></li>
<li><p><strong>Valores de VIF &gt; 10:</strong> Sugerem multicolinearidade. Variáveis como temp_med, umid_med, thr_temp, thr_umid, e thr_temp_umid apresentam VIFs extremamente altos, indicando que estão fortemente colineares com outras variáveis.</p></li>
</ul>
<p>Como temp_med, umid_med foram mais próximo de 10 retirei as thr_temp, thr_umid rodei o vif novamente, equilibrou ate 10.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Remover linhas com valores ausentes nas variáveis numéricas e manter 'Transition'</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>data_clean <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> <span class="fu">select</span>(Transition, <span class="fu">where</span>(is.numeric)) <span class="sc">%&gt;%</span> <span class="fu">drop_na</span>()</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Identificar e remover variáveis altamente colineares</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>combo_info <span class="ot">&lt;-</span> <span class="fu">findLinearCombos</span>(data_clean <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>Transition))</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">length</span>(combo_info<span class="sc">$</span>remove) <span class="sc">&gt;</span> <span class="dv">0</span>) {</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>  data_clean <span class="ot">&lt;-</span> data_clean[, <span class="sc">-</span>combo_info<span class="sc">$</span>remove]</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular o VIF para as variáveis </span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>vif_values <span class="ot">&lt;-</span> <span class="fu">vif</span>(<span class="fu">lm</span>(<span class="fu">as.numeric</span>(Transition) <span class="sc">~</span> ., <span class="at">data =</span> data_clean))</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>vif_values</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     temp_med      umid_med    precip_tot      thr_temp      thr_umid 
    18.186100     17.924880      6.225311    371.450872    189.005399 
     thr_prec thr_temp_umid      altitude         pop22    prop_esgot 
     4.917698    306.912994      2.862248      1.033193      1.920711 
 prop_residuo 
     1.887396 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Remover as variáveis thr_temp, thr_umid, e thr_temp_umid do data_clean</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>data_vif <span class="ot">&lt;-</span> data_clean <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>thr_temp, <span class="sc">-</span>thr_umid)  </span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular o VIF para as variáveis restantes</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>vif_values <span class="ot">&lt;-</span> <span class="fu">vif</span>(<span class="fu">lm</span>(<span class="fu">as.numeric</span>(Transition) <span class="sc">~</span> ., <span class="at">data =</span> data_vif))</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Exibir os valores de VIF</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>vif_values</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     temp_med      umid_med    precip_tot      thr_prec thr_temp_umid 
    10.160546      6.333997      4.595386      4.426794      5.773430 
     altitude         pop22    prop_esgot  prop_residuo 
     2.852207      1.032853      1.870609      1.864411 </code></pre>
</div>
</div>
</section>
<section id="independência-das-observações" class="level3">
<h3 class="anchored" data-anchor-id="independência-das-observações">2.2 Independência das observações</h3>
<p>Intrepretação:</p>
<p>O valor 0 indica que não foram encontradas linhas duplicadas em data_clean.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Remover linhas com valores ausentes nas variáveis numéricas e manter 'Transition'</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>data_clean <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> <span class="fu">select</span>(Transition, <span class="fu">where</span>(is.numeric)) <span class="sc">%&gt;%</span> <span class="fu">drop_na</span>()</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Remover as variáveis thr_temp, thr_umid, e thr_temp_umid do banco original (data)</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>thr_temp, <span class="sc">-</span>thr_umid)  </span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Verificar se há identificadores duplicados</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>duplicated_rows <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">duplicated</span>(data))</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>duplicated_rows</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
</section>
<section id="tamanho-amostral-adequado" class="level3">
<h3 class="anchored" data-anchor-id="tamanho-amostral-adequado">2.3 Tamanho amostral adequado</h3>
<p>Interpretação:</p>
<p>Em regressão logística multinomial, cada categoria da variável dependente precisa de um número suficiente de observações para garantir que o modelo possa estimar os parâmetros de forma confiável. Geralmente, recomenda-se pelo menos 10 a 20 observações por parâmetro estimado em cada categoria. Com 759 (Melhorou), 1.163 (Piorou) e 3.648 (Se manteve). <strong>ACHO QUE O PROBLEMA É AQUI!!!!</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Contagem de observações por categoria da variável dependente</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(data<span class="sc">$</span>Transition)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  Melhorou     Piorou Se manteve 
       759       1163       3648 </code></pre>
</div>
</div>
</section>
<section id="outliers-influentes" class="level3">
<h3 class="anchored" data-anchor-id="outliers-influentes">2.4 Outliers influentes</h3>
<p>Interpretação:</p>
<p>O código retornou valor 0 nas observações, indicando que não foram encontrados outliers com resíduos padronizados maiores que 2 ou menores que -2. Isso sugere que o modelo se ajustou bem aos dados e não há observações que se desviem significativamente do padrão previsto pelo modelo.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ajustar o modelo multinomial</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>multinom_model <span class="ot">&lt;-</span> <span class="fu">multinom</span>(Transition <span class="sc">~</span> ., <span class="at">data =</span> data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># weights:  75 (48 variable)
initial  value 6119.270448 
iter  10 value 5176.350911
iter  20 value 5088.645292
iter  30 value 4790.922409
iter  40 value 4593.203087
iter  50 value 4573.831582
iter  60 value 4572.088374
final  value 4572.067360 
converged</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular resíduos padronizados</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>residuals <span class="ot">&lt;-</span> <span class="fu">residuals</span>(multinom_model, <span class="at">type =</span> <span class="st">"pearson"</span>)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Identificar outliers com resíduos padronizados acima de 2 ou abaixo de -2</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>outliers <span class="ot">&lt;-</span> <span class="fu">which</span>(<span class="fu">abs</span>(residuals) <span class="sc">&gt;</span> <span class="dv">2</span>)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(outliers)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="do">##OUTRO</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Obter os resíduos deviance para cada observação</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>deviance_residuals <span class="ot">&lt;-</span> <span class="fu">residuals</span>(multinom_model, <span class="at">type =</span> <span class="st">"deviance"</span>)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Ponto de corte padrão da literatura</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>cutoff <span class="ot">&lt;-</span> <span class="fl">2.0</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>influential_points <span class="ot">&lt;-</span> <span class="fu">which</span>(<span class="fu">abs</span>(deviance_residuals) <span class="sc">&gt;</span> cutoff)</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(data[influential_points, ])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] Transition    temp_med      umid_med      precip_tot    thr_prec     
 [6] thr_temp_umid tipo_regiao   altitude      bioma         koppen       
[11] pop22         prop_esgot    prop_residuo 
&lt;0 linhas&gt; (ou row.names de comprimento 0)</code></pre>
</div>
</div>
</section>
</section>
<section id="ajuste-do-modelo-de-regressão-logística-multinomial" class="level2">
<h2 class="anchored" data-anchor-id="ajuste-do-modelo-de-regressão-logística-multinomial">3. Ajuste do modelo de regressão logística multinomial</h2>
<p>Interpretação:</p>
<p>Para cada categoria (em relação à referência “Se manteve”), o modelo estima coeficientes (Coefficients) para cada variável preditora. Esses coeficientes representam o efeito de cada variável sobre a probabilidade de estar na categoria Melhorou ou Piorou, em comparação com Se manteve.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Definir a categoria de referência</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>Transition <span class="ot">&lt;-</span> <span class="fu">relevel</span>(data<span class="sc">$</span>Transition, <span class="at">ref =</span> <span class="st">"Se manteve"</span>)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Ajustar o modelo</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>multinom_model <span class="ot">&lt;-</span> <span class="fu">multinom</span>(Transition <span class="sc">~</span> ., <span class="at">data =</span> data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># weights:  75 (48 variable)
initial  value 6119.270448 
iter  10 value 4821.293845
iter  20 value 4701.980308
iter  30 value 4599.987695
iter  40 value 4576.493627
iter  50 value 4572.144093
iter  60 value 4572.068284
final  value 4572.067374 
converged</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(multinom_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
multinom(formula = Transition ~ ., data = data)

Coefficients:
         (Intercept)   temp_med    umid_med    precip_tot   thr_prec
Melhorou    -6.60265  0.0673417  0.05446119 -0.0015064586 0.08488134
Piorou      11.35623 -0.2752578 -0.06067595 -0.0005165576 0.03078766
         thr_temp_umid tipo_regiaonao metropolitana      altitude biomacaatinga
Melhorou  0.0007297876                  0.101181941 -0.0001435605     0.2102398
Piorou    0.0015143131                  0.006217213 -0.0013765525    -0.9406276
         biomacerrado biomamata atlantica biomapampa biomapantanal   koppenAm
Melhorou   -0.1304372         -0.06846254 -0.1786257   -10.6661872 -0.6618383
Piorou     -0.7304452         -0.91882436 -1.4432128    -0.7809169 -0.8462770
           koppenAs   koppenAw koppenBSh  koppenCfa  koppenCfb  koppenCwa
Melhorou -0.4271992 -0.1122394 -0.570444 -1.6058189 -0.3536623 -0.3312165
Piorou   -0.7210093 -0.9855494 -1.052984 -0.6200882 -0.7736816 -1.3208518
          koppenCwb         pop22   prop_esgot prop_residuo
Melhorou  0.2613554 -3.198480e-06 -0.002257525 0.0003946671
Piorou   -1.3275590 -3.296383e-07  0.001177268 0.0018261644

Std. Errors:
          (Intercept)     temp_med     umid_med   precip_tot     thr_prec
Melhorou 3.559877e-06 7.763907e-05 0.0002006015 0.0002190683 9.041372e-06
Piorou   8.542776e-06 1.787639e-04 0.0004803206 0.0002138344 4.254115e-05
         thr_temp_umid tipo_regiaonao metropolitana     altitude biomacaatinga
Melhorou  0.0003389223                 2.812564e-06 0.0001478188  3.137561e-06
Piorou    0.0003634162                 7.760322e-06 0.0001274071  5.167866e-06
         biomacerrado biomamata atlantica   biomapampa biomapantanal
Melhorou 3.027169e-06        9.485176e-06 5.963614e-07  2.631958e-12
Piorou   2.641090e-06        6.411320e-06 3.124588e-06  1.522900e-07
             koppenAm     koppenAs     koppenAw    koppenBSh    koppenCfa
Melhorou 1.654888e-06 2.331638e-06 2.771156e-06 5.246083e-07 3.458550e-06
Piorou   2.802160e-06 3.248294e-06 2.429568e-06 1.225752e-06 1.638018e-05
            koppenCfb    koppenCwa    koppenCwb        pop22  prop_esgot
Melhorou 1.066013e-06 2.271312e-06 1.676132e-06 1.004646e-06 0.001109790
Piorou   4.405761e-07 4.805537e-06 3.726256e-06 2.940235e-07 0.001315625
         prop_residuo
Melhorou 0.0009399135
Piorou   0.0014749078

Residual Deviance: 9144.135 
AIC: 9240.135 </code></pre>
</div>
</div>
</section>
<section id="avaliação-do-ajuste-do-modelo" class="level2">
<h2 class="anchored" data-anchor-id="avaliação-do-ajuste-do-modelo">4. Avaliação do ajuste do modelo</h2>
<p>Interpretação do Pseudo R²:</p>
<p>Pseudo R² Modestos: Os valores de pseudo R² estão em torno de 6.3% a 12.6%. Isso indica que o modelo explica uma porção limitada da variabilidade dos dados, sugerindo que: As variáveis preditoras oferecem uma melhoria sobre o modelo nulo, mas podem não capturar toda a complexidade dos dados. O modelo tem algum poder explicativo, mas ainda pode ser aprimorado adicionando variáveis preditoras relevantes ou ajustando o modelo de outra maneira. Essas métricas mostram que o modelo tem um ajuste razoável, mas há espaço para melhorias se o objetivo for aumentar a explicação da variabilidade na variável Transition.</p>
<p>Interpretação do Teste de razão de verossimilhança:</p>
<p>O teste de razão de verossimilhança sugere que o modelo completo é significativamente melhor que o modelo nulo para explicar a variável Transition. Em outras palavras, as variáveis preditoras do modelo contribuem de maneira significativa para prever a categoria de Transition, justificando a inclusão delas no modelo.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Pseudo R²</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">pR2</span>(multinom_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>fitting null model for pseudo-r2
# weights:  6 (2 variable)
initial  value 6119.270448 
final  value 4878.405761 
converged</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>          llh       llhNull            G2      McFadden          r2ML 
-4.572067e+03 -4.878406e+03  6.126768e+02  6.279477e-02  1.041621e-01 
         r2CU 
 1.260255e-01 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Teste de razão de verossimilhança</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lrtest</span>(multinom_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># weights:  6 (2 variable)
initial  value 6119.270448 
final  value 4878.405761 
converged</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Likelihood ratio test

Model 1: Transition ~ temp_med + umid_med + precip_tot + thr_prec + thr_temp_umid + 
    tipo_regiao + altitude + bioma + koppen + pop22 + prop_esgot + 
    prop_residuo
Model 2: Transition ~ 1
  #Df  LogLik  Df  Chisq Pr(&gt;Chisq)    
1  48 -4572.1                          
2   2 -4878.4 -46 612.68  &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
<section id="seleção-de-variáveis" class="level2">
<h2 class="anchored" data-anchor-id="seleção-de-variáveis">5. Seleção de variáveis</h2>
<p>Interpretação:</p>
<p>Após realizar a seleção stepwise, hove redução de variáveis como thr_temp_umid, tipo_regiao, prop_esgot, e prop_residuo foram removidas, pois o processo de seleção considerou que elas não contribuem significativamente para o modelo. O modelo agora utiliza apenas as variáveis que mostraram uma contribuição estatisticamente relevante para explicar a variável Transition.</p>
<p>Residual Deviance: A deviance residual passou de 9144.135 para 9150.353. Isso representa um aumento leve, indicando que, ao reduzir variáveis, houve uma pequena perda no ajuste do modelo aos dados.</p>
<p>Já o AIC reduziu de 9240.135 para 9230.353, o que indica que o novo modelo com menos variáveis é preferível ao anterior. A redução no AIC sugere que o novo modelo oferece um bom equilíbrio entre ajuste e simplicidade.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Seleção stepwise</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>step_model <span class="ot">&lt;-</span> <span class="fu">step</span>(multinom_model, <span class="at">direction =</span> <span class="st">"both"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=9240.13
Transition ~ temp_med + umid_med + precip_tot + thr_prec + thr_temp_umid + 
    tipo_regiao + altitude + bioma + koppen + pop22 + prop_esgot + 
    prop_residuo

trying - temp_med 
# weights:  72 (46 variable)
initial  value 6119.270448 
iter  10 value 4820.688400
iter  20 value 4682.280694
iter  30 value 4613.184439
iter  40 value 4592.750600
iter  50 value 4591.702101
iter  60 value 4591.647152
iter  60 value 4591.647107
iter  60 value 4591.647107
final  value 4591.647107 
converged
trying - umid_med 
# weights:  72 (46 variable)
initial  value 6119.270448 
iter  10 value 4818.251767
iter  20 value 4708.655618
iter  30 value 4603.269110
iter  40 value 4585.499870
iter  50 value 4584.637226
iter  60 value 4584.577625
final  value 4584.577556 
converged
trying - precip_tot 
# weights:  72 (46 variable)
initial  value 6119.270448 
iter  10 value 4822.100263
iter  20 value 4731.779959
iter  30 value 4603.830966
iter  40 value 4577.280651
iter  50 value 4573.812788
iter  60 value 4573.761119
final  value 4573.760597 
converged
trying - thr_prec 
# weights:  72 (46 variable)
initial  value 6119.270448 
iter  10 value 4821.252001
iter  20 value 4684.871104
iter  30 value 4598.245199
iter  40 value 4579.050157
iter  50 value 4576.449823
iter  60 value 4576.399018
final  value 4576.398579 
converged
trying - thr_temp_umid 
# weights:  72 (46 variable)
initial  value 6119.270448 
iter  10 value 4863.287765
iter  20 value 4695.983583
iter  30 value 4587.981344
iter  40 value 4573.958016
iter  50 value 4572.870339
iter  60 value 4572.802956
final  value 4572.802203 
converged
trying - tipo_regiao 
# weights:  72 (46 variable)
initial  value 6119.270448 
iter  10 value 4821.294248
iter  20 value 4702.051892
iter  30 value 4597.764289
iter  40 value 4576.366533
iter  50 value 4572.289526
iter  60 value 4572.237374
final  value 4572.237186 
converged
trying - altitude 
# weights:  72 (46 variable)
initial  value 6119.270448 
iter  10 value 4981.421870
iter  20 value 4887.550956
iter  30 value 4629.559583
iter  40 value 4586.076837
iter  50 value 4583.824117
iter  60 value 4583.751432
final  value 4583.751137 
converged
trying - bioma 
# weights:  60 (38 variable)
initial  value 6119.270448 
iter  10 value 4821.294016
iter  20 value 4704.579614
iter  30 value 4602.661440
iter  40 value 4585.183904
final  value 4584.411166 
converged
trying - koppen 
# weights:  51 (32 variable)
initial  value 6119.270448 
iter  10 value 4821.310824
iter  20 value 4763.178882
iter  30 value 4641.435114
iter  40 value 4630.979189
iter  50 value 4630.950549
iter  50 value 4630.950509
iter  50 value 4630.950508
final  value 4630.950508 
converged
trying - pop22 
# weights:  72 (46 variable)
initial  value 6119.270448 
iter  10 value 4825.363070
iter  20 value 4717.269129
iter  30 value 4603.188928
iter  40 value 4583.115294
iter  50 value 4580.038813
iter  60 value 4579.980759
final  value 4579.980650 
converged
trying - prop_esgot 
# weights:  72 (46 variable)
initial  value 6119.270448 
iter  10 value 4794.506802
iter  20 value 4666.685071
iter  30 value 4593.750567
iter  40 value 4575.503225
iter  50 value 4573.156880
iter  60 value 4573.102174
final  value 4573.101981 
converged
trying - prop_residuo 
# weights:  72 (46 variable)
initial  value 6119.270448 
iter  10 value 4821.571497
iter  20 value 4679.880904
iter  30 value 4592.153319
iter  40 value 4574.875389
iter  50 value 4572.435083
iter  60 value 4572.384783
final  value 4572.384687 
converged
                Df      AIC
- tipo_regiao   46 9236.474
- prop_residuo  46 9236.769
- thr_temp_umid 46 9237.604
- prop_esgot    46 9238.204
- precip_tot    46 9239.521
&lt;none&gt;          48 9240.135
- thr_prec      46 9244.797
- bioma         38 9244.822
- pop22         46 9251.961
- altitude      46 9259.502
- umid_med      46 9261.155
- temp_med      46 9275.294
- koppen        32 9325.901
# weights:  72 (46 variable)
initial  value 6119.270448 
iter  10 value 4821.294248
iter  20 value 4702.051892
iter  30 value 4597.764289
iter  40 value 4576.366533
iter  50 value 4572.289526
iter  60 value 4572.237374
final  value 4572.237186 
converged

Step:  AIC=9236.47
Transition ~ temp_med + umid_med + precip_tot + thr_prec + thr_temp_umid + 
    altitude + bioma + koppen + pop22 + prop_esgot + prop_residuo

trying - temp_med 
# weights:  69 (44 variable)
initial  value 6119.270448 
iter  10 value 4820.689179
iter  20 value 4681.635988
iter  30 value 4609.692503
iter  40 value 4593.071696
iter  50 value 4591.843485
final  value 4591.816727 
converged
trying - umid_med 
# weights:  69 (44 variable)
initial  value 6119.270448 
iter  10 value 4818.254401
iter  20 value 4706.505937
iter  30 value 4602.544190
iter  40 value 4585.784560
iter  50 value 4584.788752
final  value 4584.757604 
converged
trying - precip_tot 
# weights:  69 (44 variable)
initial  value 6119.270448 
iter  10 value 4822.107424
iter  20 value 4733.555930
iter  30 value 4598.344913
iter  40 value 4576.374971
iter  50 value 4574.051681
iter  60 value 4574.018763
final  value 4574.018438 
converged
trying - thr_prec 
# weights:  69 (44 variable)
initial  value 6119.270448 
iter  10 value 4821.252450
iter  20 value 4685.560539
iter  30 value 4598.950934
iter  40 value 4579.134488
iter  50 value 4576.628486
iter  60 value 4576.599191
final  value 4576.598966 
converged
trying - thr_temp_umid 
# weights:  69 (44 variable)
initial  value 6119.270448 
iter  10 value 4863.283029
iter  20 value 4696.446642
iter  30 value 4587.053067
iter  40 value 4573.708035
iter  50 value 4573.009214
iter  60 value 4572.972265
final  value 4572.972187 
converged
trying - altitude 
# weights:  69 (44 variable)
initial  value 6119.270448 
iter  10 value 4981.433690
iter  20 value 4887.787004
iter  30 value 4618.132204
iter  40 value 4585.941108
iter  50 value 4583.968037
iter  60 value 4583.924226
iter  60 value 4583.924181
iter  60 value 4583.924181
final  value 4583.924181 
converged
trying - bioma 
# weights:  57 (36 variable)
initial  value 6119.270448 
iter  10 value 4821.294419
iter  20 value 4705.185246
iter  30 value 4599.536420
iter  40 value 4584.749820
final  value 4584.741711 
converged
trying - koppen 
# weights:  48 (30 variable)
initial  value 6119.270448 
iter  10 value 4821.311229
iter  20 value 4763.394398
iter  30 value 4632.000203
iter  40 value 4631.029868
final  value 4631.017658 
converged
trying - pop22 
# weights:  69 (44 variable)
initial  value 6119.270448 
iter  10 value 4825.369172
iter  20 value 4720.614206
iter  30 value 4598.415383
iter  40 value 4584.086360
iter  50 value 4582.030071
iter  60 value 4582.000602
final  value 4582.000476 
converged
trying - prop_esgot 
# weights:  69 (44 variable)
initial  value 6119.270448 
iter  10 value 4794.510492
iter  20 value 4667.706289
iter  30 value 4590.209432
iter  40 value 4575.340535
iter  50 value 4573.270315
final  value 4573.247339 
converged
trying - prop_residuo 
# weights:  69 (44 variable)
initial  value 6119.270448 
iter  10 value 4821.577094
iter  20 value 4680.382146
iter  30 value 4593.787475
iter  40 value 4575.697499
iter  50 value 4572.587713
iter  60 value 4572.555330
final  value 4572.555186 
converged
trying + tipo_regiao 
# weights:  75 (48 variable)
initial  value 6119.270448 
iter  10 value 4821.293845
iter  20 value 4701.980290
iter  30 value 4599.986755
iter  40 value 4576.493370
iter  50 value 4572.144086
iter  60 value 4572.068283
final  value 4572.067374 
converged
                Df      AIC
- prop_residuo  44 9233.110
- thr_temp_umid 44 9233.944
- prop_esgot    44 9234.495
- precip_tot    44 9236.037
&lt;none&gt;          46 9236.474
+ +tipo_regiao  48 9240.135
- thr_prec      44 9241.198
- bioma         36 9241.483
- pop22         44 9252.001
- altitude      44 9255.848
- umid_med      44 9257.515
- temp_med      44 9271.633
- koppen        30 9322.035
# weights:  69 (44 variable)
initial  value 6119.270448 
iter  10 value 4821.577094
iter  20 value 4680.382146
iter  30 value 4593.787475
iter  40 value 4575.697499
iter  50 value 4572.587713
iter  60 value 4572.555330
final  value 4572.555186 
converged

Step:  AIC=9233.11
Transition ~ temp_med + umid_med + precip_tot + thr_prec + thr_temp_umid + 
    altitude + bioma + koppen + pop22 + prop_esgot

trying - temp_med 
# weights:  66 (42 variable)
initial  value 6119.270448 
iter  10 value 4823.566238
iter  20 value 4695.179572
iter  30 value 4603.073849
iter  40 value 4593.335995
iter  50 value 4592.882927
final  value 4592.877208 
converged
trying - umid_med 
# weights:  66 (42 variable)
initial  value 6119.270448 
iter  10 value 4835.374363
iter  20 value 4704.196898
iter  30 value 4594.360213
iter  40 value 4586.189763
iter  50 value 4585.698035
final  value 4585.693331 
converged
trying - precip_tot 
# weights:  66 (42 variable)
initial  value 6119.270448 
iter  10 value 4836.828642
iter  20 value 4696.305048
iter  30 value 4594.687852
iter  40 value 4575.439278
iter  50 value 4574.343496
iter  60 value 4574.324102
final  value 4574.323946 
converged
trying - thr_prec 
# weights:  66 (42 variable)
initial  value 6119.270448 
iter  10 value 4821.806847
iter  20 value 4673.416565
iter  30 value 4588.970011
iter  40 value 4577.624623
iter  50 value 4576.988292
iter  60 value 4576.980599
iter  60 value 4576.980575
iter  60 value 4576.980575
final  value 4576.980575 
converged
trying - thr_temp_umid 
# weights:  66 (42 variable)
initial  value 6119.270448 
iter  10 value 4845.112816
iter  20 value 4687.223279
iter  30 value 4585.005904
iter  40 value 4573.829510
iter  50 value 4573.396149
final  value 4573.377918 
converged
trying - altitude 
# weights:  66 (42 variable)
initial  value 6119.270448 
iter  10 value 4982.060900
iter  20 value 4769.712579
iter  30 value 4601.157931
iter  40 value 4585.515227
iter  50 value 4584.837307
final  value 4584.825544 
converged
trying - bioma 
# weights:  54 (34 variable)
initial  value 6119.270448 
iter  10 value 4821.582976
iter  20 value 4686.124219
iter  30 value 4599.378951
iter  40 value 4584.857831
final  value 4584.856165 
converged
trying - koppen 
# weights:  45 (28 variable)
initial  value 6119.270448 
iter  10 value 4821.619049
iter  20 value 4741.180188
iter  30 value 4632.065278
iter  40 value 4631.885906
final  value 4631.883270 
converged
trying - pop22 
# weights:  66 (42 variable)
initial  value 6119.270448 
iter  10 value 4820.605532
iter  20 value 4697.197988
iter  30 value 4593.277564
iter  40 value 4583.401298
iter  50 value 4582.647039
final  value 4582.638867 
converged
trying - prop_esgot 
# weights:  66 (42 variable)
initial  value 6119.270448 
iter  10 value 4832.623047
iter  20 value 4729.246721
iter  30 value 4594.451590
iter  40 value 4575.243713
iter  50 value 4574.270286
final  value 4574.256539 
converged
trying + tipo_regiao 
# weights:  72 (46 variable)
initial  value 6119.270448 
iter  10 value 4821.571497
iter  20 value 4679.880831
iter  30 value 4592.151165
iter  40 value 4574.875398
iter  50 value 4572.435070
iter  60 value 4572.384783
final  value 4572.384687 
converged
trying + prop_residuo 
# weights:  72 (46 variable)
initial  value 6119.270448 
iter  10 value 4821.294248
iter  20 value 4702.051892
iter  30 value 4597.764289
iter  40 value 4576.366533
iter  50 value 4572.289526
iter  60 value 4572.237374
final  value 4572.237186 
converged
                Df      AIC
- thr_temp_umid 42 9230.756
- prop_esgot    42 9232.513
- precip_tot    42 9232.648
&lt;none&gt;          44 9233.110
+ +prop_residuo 46 9236.474
+ +tipo_regiao  46 9236.769
- bioma         34 9237.712
- thr_prec      42 9237.961
- pop22         42 9249.278
- altitude      42 9253.651
- umid_med      42 9255.387
- temp_med      42 9269.754
- koppen        28 9319.767
# weights:  66 (42 variable)
initial  value 6119.270448 
iter  10 value 4845.112816
iter  20 value 4687.223279
iter  30 value 4585.005904
iter  40 value 4573.829510
iter  50 value 4573.396149
final  value 4573.377918 
converged

Step:  AIC=9230.76
Transition ~ temp_med + umid_med + precip_tot + thr_prec + altitude + 
    bioma + koppen + pop22 + prop_esgot

trying - temp_med 
# weights:  63 (40 variable)
initial  value 6119.270448 
iter  10 value 4847.343036
iter  20 value 4648.946252
iter  30 value 4606.697532
iter  40 value 4601.318972
iter  50 value 4601.126179
final  value 4601.124305 
converged
trying - umid_med 
# weights:  63 (40 variable)
initial  value 6119.270448 
iter  10 value 4809.604239
iter  20 value 4648.854857
iter  30 value 4606.010443
iter  40 value 4602.506779
iter  50 value 4602.314567
final  value 4602.313207 
converged
trying - precip_tot 
# weights:  63 (40 variable)
initial  value 6119.270448 
iter  10 value 4891.675667
iter  20 value 4667.967598
iter  30 value 4583.975655
iter  40 value 4576.263822
iter  50 value 4576.066257
final  value 4576.061887 
converged
trying - thr_prec 
# weights:  63 (40 variable)
initial  value 6119.270448 
iter  10 value 4848.754134
iter  20 value 4626.996083
iter  30 value 4583.299108
iter  40 value 4578.337988
iter  50 value 4578.190617
final  value 4578.187533 
converged
trying - altitude 
# weights:  63 (40 variable)
initial  value 6119.270448 
iter  10 value 5069.286451
iter  20 value 4778.089366
iter  30 value 4615.477348
iter  40 value 4585.531238
iter  50 value 4585.004927
final  value 4584.995239 
converged
trying - bioma 
# weights:  51 (32 variable)
initial  value 6119.270448 
iter  10 value 4845.174154
iter  20 value 4670.196851
iter  30 value 4588.573776
iter  40 value 4586.031956
iter  40 value 4586.031928
iter  40 value 4586.031928
final  value 4586.031928 
converged
trying - koppen 
# weights:  42 (26 variable)
initial  value 6119.270448 
iter  10 value 4845.516366
iter  20 value 4728.067959
iter  30 value 4632.813926
iter  40 value 4632.746951
final  value 4632.746580 
converged
trying - pop22 
# weights:  63 (40 variable)
initial  value 6119.270448 
iter  10 value 4813.887514
iter  20 value 4632.741677
iter  30 value 4587.685075
iter  40 value 4583.597117
iter  50 value 4583.412499
final  value 4583.410905 
converged
trying - prop_esgot 
# weights:  63 (40 variable)
initial  value 6119.270448 
iter  10 value 4790.490676
iter  20 value 4631.974841
iter  30 value 4580.371881
iter  40 value 4575.327193
iter  50 value 4575.179132
final  value 4575.176669 
converged
trying + thr_temp_umid 
# weights:  69 (44 variable)
initial  value 6119.270448 
iter  10 value 4821.577094
iter  20 value 4680.382196
iter  30 value 4593.788455
iter  40 value 4575.696586
iter  50 value 4572.587711
iter  60 value 4572.555330
final  value 4572.555186 
converged
trying + tipo_regiao 
# weights:  69 (44 variable)
initial  value 6119.270448 
iter  10 value 4845.128389
iter  20 value 4688.375664
iter  30 value 4587.990393
iter  40 value 4574.041943
iter  50 value 4573.249358
iter  60 value 4573.210151
final  value 4573.210067 
converged
trying + prop_residuo 
# weights:  69 (44 variable)
initial  value 6119.270448 
iter  10 value 4863.283029
iter  20 value 4696.446642
iter  30 value 4587.053067
iter  40 value 4573.708035
iter  50 value 4573.009214
iter  60 value 4572.972265
final  value 4572.972187 
converged
                 Df      AIC
- prop_esgot     40 9230.353
&lt;none&gt;           42 9230.756
- precip_tot     40 9232.124
+ +thr_temp_umid 44 9233.110
+ +prop_residuo  44 9233.944
+ +tipo_regiao   44 9234.420
- bioma          32 9236.064
- thr_prec       40 9236.375
- pop22          40 9246.822
- altitude       40 9249.990
- temp_med       40 9282.249
- umid_med       40 9284.626
- koppen         26 9317.493
# weights:  63 (40 variable)
initial  value 6119.270448 
iter  10 value 4790.490676
iter  20 value 4631.974841
iter  30 value 4580.371881
iter  40 value 4575.327193
iter  50 value 4575.179132
final  value 4575.176669 
converged

Step:  AIC=9230.35
Transition ~ temp_med + umid_med + precip_tot + thr_prec + altitude + 
    bioma + koppen + pop22

trying - temp_med 
# weights:  60 (38 variable)
initial  value 6119.270448 
iter  10 value 4830.125869
iter  20 value 4641.990216
iter  30 value 4609.136502
iter  40 value 4607.311303
iter  50 value 4607.216204
final  value 4607.215926 
converged
trying - umid_med 
# weights:  60 (38 variable)
initial  value 6119.270448 
iter  10 value 4799.877184
iter  20 value 4640.284016
iter  30 value 4609.859986
iter  40 value 4607.907437
iter  50 value 4607.776255
final  value 4607.775880 
converged
trying - precip_tot 
# weights:  60 (38 variable)
initial  value 6119.270448 
iter  10 value 4871.323555
iter  20 value 4668.627745
iter  30 value 4585.276556
iter  40 value 4578.050025
iter  50 value 4577.919510
final  value 4577.917584 
converged
trying - thr_prec 
# weights:  60 (38 variable)
initial  value 6119.270448 
iter  10 value 4815.336928
iter  20 value 4619.801286
iter  30 value 4582.201974
iter  40 value 4580.108707
iter  50 value 4580.023065
final  value 4580.021981 
converged
trying - altitude 
# weights:  60 (38 variable)
initial  value 6119.270448 
iter  10 value 5032.669592
iter  20 value 4756.152572
iter  30 value 4598.578149
iter  40 value 4588.695466
iter  50 value 4588.558249
final  value 4588.556988 
converged
trying - bioma 
# weights:  48 (30 variable)
initial  value 6119.270448 
iter  10 value 4791.024610
iter  20 value 4621.700237
iter  30 value 4589.726470
final  value 4587.388290 
converged
trying - koppen 
# weights:  39 (24 variable)
initial  value 6119.270448 
iter  10 value 4793.566326
iter  20 value 4665.450798
iter  30 value 4632.808641
final  value 4632.773805 
converged
trying - pop22 
# weights:  60 (38 variable)
initial  value 6119.270448 
iter  10 value 4801.674164
iter  20 value 4645.719191
iter  30 value 4591.053800
iter  40 value 4587.929931
iter  50 value 4587.855981
final  value 4587.855163 
converged
trying + thr_temp_umid 
# weights:  66 (42 variable)
initial  value 6119.270448 
iter  10 value 4832.623047
iter  20 value 4729.246555
iter  30 value 4594.450563
iter  40 value 4575.243774
iter  50 value 4574.270282
final  value 4574.256539 
converged
trying + tipo_regiao 
# weights:  66 (42 variable)
initial  value 6119.270448 
iter  10 value 4790.441139
iter  20 value 4636.472511
iter  30 value 4580.447911
iter  40 value 4575.396931
iter  50 value 4575.008831
final  value 4574.993703 
converged
trying + prop_esgot 
# weights:  66 (42 variable)
initial  value 6119.270448 
iter  10 value 4845.112816
iter  20 value 4687.223279
iter  30 value 4585.005904
iter  40 value 4573.829510
iter  50 value 4573.396149
final  value 4573.377918 
converged
trying + prop_residuo 
# weights:  66 (42 variable)
initial  value 6119.270448 
iter  10 value 4877.713872
iter  20 value 4703.706710
iter  30 value 4585.592304
iter  40 value 4574.390701
iter  50 value 4574.009563
final  value 4573.986772 
converged
                 Df      AIC
&lt;none&gt;           40 9230.353
+ +prop_esgot    42 9230.756
- precip_tot     38 9231.835
+ +prop_residuo  42 9231.974
+ +thr_temp_umid 42 9232.513
+ +tipo_regiao   42 9233.987
- bioma          30 9234.777
- thr_prec       38 9236.044
- pop22          38 9251.710
- altitude       38 9253.114
- temp_med       38 9290.432
- umid_med       38 9291.552
- koppen         24 9313.548</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(step_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
multinom(formula = Transition ~ temp_med + umid_med + precip_tot + 
    thr_prec + altitude + bioma + koppen + pop22, data = data)

Coefficients:
         (Intercept)    temp_med    umid_med    precip_tot   thr_prec
Melhorou   -7.543784  0.09120583  0.06425597 -0.0017413135 0.08835100
Piorou     10.491858 -0.24974700 -0.04839622 -0.0006624192 0.02249701
              altitude biomacaatinga biomacerrado biomamata atlantica
Melhorou -6.218794e-05     0.1674847   -0.1478257          -0.1346374
Piorou   -1.355043e-03    -0.9532043   -0.7078651          -0.8493454
         biomapampa biomapantanal   koppenAm   koppenAs   koppenAw  koppenBSh
Melhorou -0.2456062   -10.3845414 -0.6605685 -0.4396557 -0.1290507 -0.5968123
Piorou   -1.4010083    -0.8020613 -0.8463208 -0.7601719 -0.9842816 -1.0762646
          koppenCfa  koppenCfb  koppenCwa  koppenCwb         pop22
Melhorou -1.6074134 -0.4220192 -0.3800654  0.1939392 -3.709962e-06
Piorou   -0.6569542 -0.8782497 -1.2669002 -1.3376694 -2.187257e-07

Std. Errors:
          (Intercept)     temp_med    umid_med   precip_tot     thr_prec
Melhorou 2.197173e-05 0.0006216012 0.001525505 0.0002558271 4.437734e-05
Piorou   2.446701e-05 0.0006877274 0.001621068 0.0002645234 4.499478e-05
             altitude biomacaatinga biomacerrado biomamata atlantica
Melhorou 0.0001300371  2.277997e-05 1.735285e-06        1.754239e-06
Piorou   0.0001215559  2.046161e-05 2.875693e-06        2.766669e-06
           biomapampa biomapantanal     koppenAm     koppenAs     koppenAw
Melhorou 1.518208e-07  3.807712e-12 1.378797e-06 1.784193e-05 7.684005e-06
Piorou   2.414100e-06  1.715805e-07 5.570005e-07 1.593864e-05 1.001250e-05
            koppenBSh    koppenCfa    koppenCfb    koppenCwa    koppenCwb
Melhorou 8.359144e-06 2.487865e-07 3.531296e-06 1.169345e-06 5.105752e-06
Piorou   7.922812e-06 2.058489e-06 6.861048e-06 7.024724e-07 3.358376e-06
                pop22
Melhorou 9.973602e-07
Piorou   2.514283e-07

Residual Deviance: 9150.353 
AIC: 9230.353 </code></pre>
</div>
</div>
<section id="matriz-de-confusão-do-stepwise" class="level3">
<h3 class="anchored" data-anchor-id="matriz-de-confusão-do-stepwise">5.1 Matriz de confusão do stepwise</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># previsoes</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>previsoes <span class="ot">&lt;-</span> <span class="fu">predict</span>(step_model, <span class="at">newdata =</span> data)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="co"># matriz de confusão comparando as previsões com os valores reais</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>matriz_confusao <span class="ot">&lt;-</span> <span class="fu">confusionMatrix</span>(previsoes, data<span class="sc">$</span>Transition)</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(matriz_confusao)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

            Reference
Prediction   Se manteve Melhorou Piorou
  Se manteve       3580      753   1094
  Melhorou            0        0      0
  Piorou             68        6     69

Overall Statistics
                                          
               Accuracy : 0.6551          
                 95% CI : (0.6425, 0.6676)
    No Information Rate : 0.6549          
    P-Value [Acc &gt; NIR] : 0.495           
                                          
                  Kappa : 0.0326          
                                          
 Mcnemar's Test P-Value : &lt;2e-16          

Statistics by Class:

                     Class: Se manteve Class: Melhorou Class: Piorou
Sensitivity                    0.98136          0.0000       0.05933
Specificity                    0.03902          1.0000       0.98321
Pos Pred Value                 0.65966             NaN       0.48252
Neg Pred Value                 0.52448          0.8637       0.79842
Prevalence                     0.65494          0.1363       0.20880
Detection Rate                 0.64273          0.0000       0.01239
Detection Prevalence           0.97433          0.0000       0.02567
Balanced Accuracy              0.51019          0.5000       0.52127</code></pre>
</div>
</div>
</section>
</section>
<section id="análise-de-resíduos" class="level2">
<h2 class="anchored" data-anchor-id="análise-de-resíduos">6. Análise de resíduos</h2>
<p>PESSÍMA</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Resíduos deviance</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>residuals_deviance <span class="ot">&lt;-</span> <span class="fu">residuals</span>(step_model, <span class="at">type =</span> <span class="st">"deviance"</span>)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(residuals_deviance, <span class="at">main =</span> <span class="st">"Resíduos Deviance"</span>, <span class="at">ylab =</span> <span class="st">"Resíduos"</span>, <span class="at">xlab =</span> <span class="st">"Observações"</span>)</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">0</span>, <span class="at">col =</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analise_regressao_multinomial_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="do">### OUTRO</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular os resíduos deviance</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>residuals_deviance <span class="ot">&lt;-</span> <span class="fu">residuals</span>(step_model, <span class="at">type =</span> <span class="st">"deviance"</span>)</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Função para gerar um QQ plot com envelope</span></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a><span class="fu">qqPlot</span>(residuals_deviance, </span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">main =</span> <span class="st">"QQ Plot dos Resíduos com Envelope de Confiança"</span>,</span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">xlab =</span> <span class="st">"Quantis Teóricos"</span>,</span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">ylab =</span> <span class="st">"Resíduos"</span>,</span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">id =</span> <span class="cn">FALSE</span>, <span class="co"># Desativar a identificação de pontos</span></span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">envelope =</span> <span class="fl">0.95</span>) <span class="co"># Adicionar envelope de confiança de 95%</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analise_regressao_multinomial_files/figure-html/unnamed-chunk-10-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="interpretação-dos-resultados" class="level2">
<h2 class="anchored" data-anchor-id="interpretação-dos-resultados">7. Interpretação dos resultados</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Coeficientes e intervalos de confiança</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>tidy_model <span class="ot">&lt;-</span> <span class="fu">tidy</span>(step_model, <span class="at">conf.int =</span> <span class="cn">TRUE</span>)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>tidy_model</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 40 × 8
   y.level  term        estimate std.error statistic  p.value conf.low conf.high
   &lt;chr&gt;    &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
 1 Melhorou (Intercept) -7.54e+0   2.20e-5  -3.43e+5 0        -7.54e+0 -7.54    
 2 Melhorou temp_med     9.12e-2   6.22e-4   1.47e+2 0         9.00e-2  0.0924  
 3 Melhorou umid_med     6.43e-2   1.53e-3   4.21e+1 0         6.13e-2  0.0672  
 4 Melhorou precip_tot  -1.74e-3   2.56e-4  -6.81e+0 9.99e-12 -2.24e-3 -0.00124 
 5 Melhorou thr_prec     8.84e-2   4.44e-5   1.99e+3 0         8.83e-2  0.0884  
 6 Melhorou altitude    -6.22e-5   1.30e-4  -4.78e-1 6.32e- 1 -3.17e-4  0.000193
 7 Melhorou biomacaati…  1.67e-1   2.28e-5   7.35e+3 0         1.67e-1  0.168   
 8 Melhorou biomacerra… -1.48e-1   1.74e-6  -8.52e+4 0        -1.48e-1 -0.148   
 9 Melhorou biomamata … -1.35e-1   1.75e-6  -7.67e+4 0        -1.35e-1 -0.135   
10 Melhorou biomapampa  -2.46e-1   1.52e-7  -1.62e+6 0        -2.46e-1 -0.246   
# ℹ 30 more rows</code></pre>
</div>
</div>
</section>
</section>
<section id="análise-2" class="level1">
<h1>ANÁLISE 2</h1>
<p>Análise com combinações de variáveis.</p>
<section id="carregando-os-dados-1" class="level2">
<h2 class="anchored" data-anchor-id="carregando-os-dados-1">1. Carregando os dados</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Carregar os dados</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"det_transicao.csv"</span>, <span class="at">sep =</span> <span class="st">";"</span>)</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a><span class="do">## Selecionando variáveis</span></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "muni_code"            "dengue_pattern_10_19" "dengue_pattern_20_22"
 [4] "Transition"           "temp_med"             "umid_med"            
 [7] "precip_tot"           "thr_temp"             "thr_umid"            
[10] "thr_prec"             "thr_temp_umid"        "muni_name"           
[13] "uf_code"              "uf_acr"               "tipo_regiao"         
[16] "bioma"                "altitude"             "koppen"              
[19] "pop22"                "prop_esgot"           "prop_abast"          
[22] "prop_residuo"        </code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Lista de variáveis para selecionar</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>variaveis <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Transition"</span>, <span class="st">"temp_med"</span>, <span class="st">"umid_med"</span>, <span class="st">"precip_tot"</span>,</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>               <span class="st">"thr_temp"</span>, <span class="st">"thr_umid"</span>, <span class="st">"thr_prec"</span>, <span class="st">"thr_temp_umid"</span>,</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>               <span class="st">"tipo_regiao"</span>, <span class="st">"altitude"</span>,<span class="st">"bioma"</span>, <span class="st">"koppen"</span>, <span class="st">"pop22"</span>,</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>               <span class="st">"prop_esgot"</span>, <span class="st">"prop_residuo"</span>)</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Criando o novo banco de dados apenas com as variáveis selecionadas</span></span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data[, variaveis]</span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Visão geral dos dados</span></span>
<span id="cb41-12"><a href="#cb41-12" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 5,570
Columns: 15
$ Transition    &lt;chr&gt; "Piorou", "Se manteve", "Se manteve", "Se manteve", "Se …
$ temp_med      &lt;chr&gt; "25,5", "26,1", "25,3", "25,8", "25,4", "25,1", "25,2", …
$ umid_med      &lt;chr&gt; "75,7", "78,1", "75,9", "76,7", "75,7", "75,6", "76,2", …
$ precip_tot    &lt;chr&gt; "591,3", "625,5", "479,8", "639,2", "505,2", "542,1", "5…
$ thr_temp      &lt;chr&gt; "361", "365", "356,7", "363", "357", "357", "358", "359,…
$ thr_umid      &lt;chr&gt; "307,7", "324,7", "319,7", "319,7", "317,3", "312,7", "3…
$ thr_prec      &lt;chr&gt; "5", "5", "3", "6,3", "4", "5", "4", "4,3", "4", "5", "7…
$ thr_temp_umid &lt;chr&gt; "305,3", "324", "314", "317,7", "311,7", "307,7", "312,3…
$ tipo_regiao   &lt;chr&gt; "nao metropolitana", "nao metropolitana", "nao metropoli…
$ altitude      &lt;chr&gt; "246,08", "165,9", "224,18", "229,95", "192,22", "359,62…
$ bioma         &lt;chr&gt; "amazonia", "amazonia", "amazonia", "amazonia", "amazoni…
$ koppen        &lt;chr&gt; "Am", "Am", "Am", "Am", "Am", "Am", "Am", "Am", "Am", "A…
$ pop22         &lt;int&gt; 21558, 100896, 5107, 92202, 15237, 15747, 7503, 12633, 2…
$ prop_esgot    &lt;chr&gt; "2,24", "8,91", "21,01", "54,03", "16,73", "5,17", "11,5…
$ prop_residuo  &lt;chr&gt; "56,86", "85,14", "49,77", "78,94", "78,35", "69,11", "3…</code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Transition          temp_med           umid_med          precip_tot       
 Length:5570        Length:5570        Length:5570        Length:5570       
 Class :character   Class :character   Class :character   Class :character  
 Mode  :character   Mode  :character   Mode  :character   Mode  :character  
                                                                            
                                                                            
                                                                            
   thr_temp           thr_umid           thr_prec         thr_temp_umid     
 Length:5570        Length:5570        Length:5570        Length:5570       
 Class :character   Class :character   Class :character   Class :character  
 Mode  :character   Mode  :character   Mode  :character   Mode  :character  
                                                                            
                                                                            
                                                                            
 tipo_regiao          altitude            bioma              koppen         
 Length:5570        Length:5570        Length:5570        Length:5570       
 Class :character   Class :character   Class :character   Class :character  
 Mode  :character   Mode  :character   Mode  :character   Mode  :character  
                                                                            
                                                                            
                                                                            
     pop22           prop_esgot        prop_residuo      
 Min.   :     836   Length:5570        Length:5570       
 1st Qu.:    5282   Class :character   Class :character  
 Median :   11096   Mode  :character   Mode  :character  
 Mean   :   37298                                        
 3rd Qu.:   24615                                        
 Max.   :12200180                                        </code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Identificar e remover colunas completamente vazias ou com alta quantidade de NA</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> <span class="fu">select_if</span>(<span class="sc">~</span> <span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(.)) <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="do">## nenhuma foi</span></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Converter variáveis numéricas com vírgula decimal e categorizar as variáveis de texto</span></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">across</span>(<span class="fu">where</span>(<span class="sc">~</span> <span class="fu">all</span>(<span class="fu">grepl</span>(<span class="st">"^[0-9,.]+$"</span>, .))), <span class="sc">~</span> <span class="fu">as.numeric</span>(<span class="fu">gsub</span>(<span class="st">","</span>, <span class="st">"."</span>, .))),</span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">across</span>(<span class="fu">where</span>(is.character), as.factor)</span>
<span id="cb45-9"><a href="#cb45-9" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="variáveis-combinadas" class="level2">
<h2 class="anchored" data-anchor-id="variáveis-combinadas">2. Variáveis combinadas</h2>
<p>Variáveis combinadas pensando na literatura:</p>
<ol type="1">
<li><strong><em>Determinantes ecológicos :</em></strong></li>
</ol>
<ul>
<li><p>temp_med * umid_med</p></li>
<li><p>temp_med * precip_tot: Relação entre temperatura e precipitação total, que pode refletir em áreas mais propensas a surtos em climas quentes e chuvosos.</p></li>
</ul>
<ol start="2" type="1">
<li><strong><em>Determinantes eco-sociais :</em></strong></li>
</ol>
<ul>
<li><p>pop22 * prop_esgot: População combinada com a proporção de saneamento pode influenciar diretamente o ambiente, tornando-o mais ou menos favorável ao mosquito.</p></li>
<li><p>pop22 * prop_residuo: Avalia o impacto do manejo de resíduos sólidos em áreas de alta densidade populacional.</p></li>
<li><p>Logaritmo da População : O log pode normalizar a escala populacional.</p></li>
</ul>
<p><strong><em>3.Variáveis: Dummies para Categorias :</em></strong></p>
<p>Transformei variáveis como bioma e koppen em dummies para capturar efeitos fixos das categorias.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># determinantes ecológicos</span></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">temp_umid_interaction =</span> temp_med <span class="sc">*</span> umid_med,</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">temp_precip_interaction =</span> temp_med <span class="sc">*</span> precip_tot,</span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>         </span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>         <span class="co"># determinantes eco_sociais</span></span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">pop_esgot_interaction =</span> pop22 <span class="sc">*</span> prop_esgot,</span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">pop_residuo_interaction =</span> pop22 <span class="sc">*</span> prop_residuo,</span>
<span id="cb46-9"><a href="#cb46-9" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb46-10"><a href="#cb46-10" aria-hidden="true" tabindex="-1"></a>         <span class="co"># Transformações individuais</span></span>
<span id="cb46-11"><a href="#cb46-11" aria-hidden="true" tabindex="-1"></a>         <span class="at">log_pop22 =</span> <span class="fu">log</span>(pop22))</span>
<span id="cb46-12"><a href="#cb46-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-13"><a href="#cb46-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Criando variáveis dummies para categorias</span></span>
<span id="cb46-14"><a href="#cb46-14" aria-hidden="true" tabindex="-1"></a>dummy_vars <span class="ot">&lt;-</span> <span class="fu">dummyVars</span>(<span class="st">" ~ bioma + koppen"</span>, <span class="at">data =</span> data)</span>
<span id="cb46-15"><a href="#cb46-15" aria-hidden="true" tabindex="-1"></a>dados_dummies <span class="ot">&lt;-</span> <span class="fu">predict</span>(dummy_vars, <span class="at">newdata =</span> data)</span>
<span id="cb46-16"><a href="#cb46-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-17"><a href="#cb46-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Combinando as variáveis dummies ao dataset original</span></span>
<span id="cb46-18"><a href="#cb46-18" aria-hidden="true" tabindex="-1"></a>data_comb <span class="ot">&lt;-</span> <span class="fu">cbind</span>(data, dados_dummies)</span>
<span id="cb46-19"><a href="#cb46-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-20"><a href="#cb46-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Verificando as primeiras linhas para confirmar as transformações</span></span>
<span id="cb46-21"><a href="#cb46-21" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data_comb)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Transition temp_med umid_med precip_tot thr_temp thr_umid thr_prec
1     Piorou     25.5     75.7      591.3    361.0    307.7      5.0
2 Se manteve     26.1     78.1      625.5    365.0    324.7      5.0
3 Se manteve     25.3     75.9      479.8    356.7    319.7      3.0
4 Se manteve     25.8     76.7      639.2    363.0    319.7      6.3
5 Se manteve     25.4     75.7      505.2    357.0    317.3      4.0
6 Se manteve     25.1     75.6      542.1    357.0    312.7      5.0
  thr_temp_umid       tipo_regiao altitude    bioma koppen  pop22 prop_esgot
1         305.3 nao metropolitana   246.08 amazonia     Am  21558       2.24
2         324.0 nao metropolitana   165.90 amazonia     Am 100896       8.91
3         314.0 nao metropolitana   224.18 amazonia     Am   5107      21.01
4         317.7     metropolitana   229.95 amazonia     Am  92202      54.03
5         311.7 nao metropolitana   192.22 amazonia     Am  15237      16.73
6         307.7 nao metropolitana   359.62 amazonia     Am  15747       5.17
  prop_residuo temp_umid_interaction temp_precip_interaction
1        56.86               1930.35                15078.15
2        85.14               2038.41                16325.55
3        49.77               1920.27                12138.94
4        78.94               1978.86                16491.36
5        78.35               1922.78                12832.08
6        69.11               1897.56                13606.71
  pop_esgot_interaction pop_residuo_interaction log_pop22 bioma.amazonia
1              48289.92               1225787.9  9.978502              1
2             898983.36               8590285.4 11.521846              1
3             107298.07                254175.4  8.538367              1
4            4981674.06               7278425.9 11.431737              1
5             254915.01               1193818.9  9.631482              1
6              81411.99               1088275.2  9.664405              1
  bioma.caatinga bioma.cerrado bioma.mata atlantica bioma.pampa bioma.pantanal
1              0             0                    0           0              0
2              0             0                    0           0              0
3              0             0                    0           0              0
4              0             0                    0           0              0
5              0             0                    0           0              0
6              0             0                    0           0              0
  koppen.Af koppen.Am koppen.As koppen.Aw koppen.BSh koppen.Cfa koppen.Cfb
1         0         1         0         0          0          0          0
2         0         1         0         0          0          0          0
3         0         1         0         0          0          0          0
4         0         1         0         0          0          0          0
5         0         1         0         0          0          0          0
6         0         1         0         0          0          0          0
  koppen.Cwa koppen.Cwb
1          0          0
2          0          0
3          0          0
4          0          0
5          0          0
6          0          0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Converter variáveis numéricas com vírgula decimal e categorizar as variáveis de texto</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>data_comb <span class="ot">&lt;-</span> data_comb <span class="sc">%&gt;%</span></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">across</span>(<span class="fu">where</span>(<span class="sc">~</span> <span class="fu">all</span>(<span class="fu">grepl</span>(<span class="st">"^[0-9,.]+$"</span>, .))), <span class="sc">~</span> <span class="fu">as.numeric</span>(<span class="fu">gsub</span>(<span class="st">","</span>, <span class="st">"."</span>, .))),</span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">across</span>(<span class="fu">where</span>(is.character), as.factor)</span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="verificação-dos-pressupostos-1" class="level2">
<h2 class="anchored" data-anchor-id="verificação-dos-pressupostos-1">3. Verificação dos pressupostos</h2>
<section id="independência-das-observações-1" class="level3">
<h3 class="anchored" data-anchor-id="independência-das-observações-1">3.1 Independência das observações</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Verificar se há identificadores duplicados</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>duplicated_rows <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">duplicated</span>(data))</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>duplicated_rows</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
</section>
<section id="tamanho-amostral-adequado-1" class="level3">
<h3 class="anchored" data-anchor-id="tamanho-amostral-adequado-1">3.2 Tamanho amostral adequado</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Contagem de observações por categoria da variável dependente</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(data<span class="sc">$</span>Transition)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  Melhorou     Piorou Se manteve 
       759       1163       3648 </code></pre>
</div>
</div>
</section>
<section id="outliers-influentes-1" class="level3">
<h3 class="anchored" data-anchor-id="outliers-influentes-1">3.3 Outliers influentes</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ajustar o modelo multinomial</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>multinom_model <span class="ot">&lt;-</span> <span class="fu">multinom</span>(Transition <span class="sc">~</span> ., <span class="at">data =</span> data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># weights:  96 (62 variable)
initial  value 6119.270448 
iter  10 value 5034.862990
iter  20 value 4897.004119
iter  30 value 4844.555624
iter  40 value 4700.327482
iter  50 value 4671.457233
iter  60 value 4649.025390
iter  70 value 4603.739495
iter  80 value 4581.298994
iter  90 value 4578.304725
iter 100 value 4578.036179
final  value 4578.036179 
stopped after 100 iterations</code></pre>
</div>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular resíduos padronizados</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>residuals <span class="ot">&lt;-</span> <span class="fu">residuals</span>(multinom_model, <span class="at">type =</span> <span class="st">"pearson"</span>)</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Identificar outliers com resíduos padronizados acima de 2 ou abaixo de -2</span></span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>outliers <span class="ot">&lt;-</span> <span class="fu">which</span>(<span class="fu">abs</span>(residuals) <span class="sc">&gt;</span> <span class="dv">2</span>)</span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(outliers)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="do">##OUTRO</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Obter os resíduos deviance para cada observação</span></span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>deviance_residuals <span class="ot">&lt;-</span> <span class="fu">residuals</span>(multinom_model, <span class="at">type =</span> <span class="st">"deviance"</span>)</span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a>cutoff <span class="ot">&lt;-</span> <span class="fl">2.0</span></span>
<span id="cb57-7"><a href="#cb57-7" aria-hidden="true" tabindex="-1"></a>influential_points <span class="ot">&lt;-</span> <span class="fu">which</span>(<span class="fu">abs</span>(deviance_residuals) <span class="sc">&gt;</span> cutoff)</span>
<span id="cb57-8"><a href="#cb57-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-9"><a href="#cb57-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Exibir as observações influentes</span></span>
<span id="cb57-10"><a href="#cb57-10" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(data[influential_points, ])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] Transition              temp_med                umid_med               
 [4] precip_tot              thr_temp                thr_umid               
 [7] thr_prec                thr_temp_umid           tipo_regiao            
[10] altitude                bioma                   koppen                 
[13] pop22                   prop_esgot              prop_residuo           
[16] temp_umid_interaction   temp_precip_interaction pop_esgot_interaction  
[19] pop_residuo_interaction log_pop22              
&lt;0 linhas&gt; (ou row.names de comprimento 0)</code></pre>
</div>
</div>
</section>
</section>
<section id="ajuste-do-modelo-de-regressão-logística-multinomial-1" class="level2">
<h2 class="anchored" data-anchor-id="ajuste-do-modelo-de-regressão-logística-multinomial-1">4. Ajuste do modelo de regressão logística multinomial</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Definir a categoria de referência</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>Transition <span class="ot">&lt;-</span> <span class="fu">relevel</span>(data<span class="sc">$</span>Transition, <span class="at">ref =</span> <span class="st">"Se manteve"</span>)</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Ajustar o modelo</span></span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>multinom_model <span class="ot">&lt;-</span> <span class="fu">multinom</span>(Transition <span class="sc">~</span> ., <span class="at">data =</span> data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># weights:  96 (62 variable)
initial  value 6119.270448 
iter  10 value 5107.282832
iter  20 value 5007.717906
iter  30 value 4964.788006
iter  40 value 4655.495840
iter  50 value 4581.956804
iter  60 value 4570.433401
iter  70 value 4546.636552
iter  80 value 4545.410853
final  value 4545.409691 
converged</code></pre>
</div>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(multinom_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
multinom(formula = Transition ~ ., data = data)

Coefficients:
         (Intercept)  temp_med   umid_med   precip_tot     thr_temp
Melhorou   -45.22226  2.010228  0.7020227 -0.011933626 -0.013961289
Piorou      32.04468 -1.186375 -0.3337744  0.002602249 -0.005837351
             thr_umid   thr_prec thr_temp_umid tipo_regiaonao metropolitana
Melhorou -0.009771514 0.05364636   0.020700598                 0.0808047471
Piorou   -0.007995912 0.03206508   0.002411417                -0.0007205501
              altitude biomacaatinga biomacerrado biomamata atlantica
Melhorou -0.0002421857  -0.004237857   -0.2284543          -0.1600291
Piorou   -0.0013110155  -0.745670412   -0.6568546          -0.8840128
         biomapampa biomapantanal   koppenAm   koppenAs   koppenAw  koppenBSh
Melhorou -0.1319241    -9.0057685 -0.7127797 -0.3783156 -0.2377039 -0.6338893
Piorou   -1.4670067    -0.6108177 -0.7781452 -0.7238552 -0.8218299 -0.9461549
          koppenCfa  koppenCfb  koppenCwa koppenCwb         pop22   prop_esgot
Melhorou -1.3795823 -0.2912348 -0.2765903  0.472729  3.431248e-06 -0.003557368
Piorou   -0.6986013 -0.8578849 -1.3171237 -1.449164 -1.216881e-05  0.002087151
         prop_residuo temp_umid_interaction temp_precip_interaction
Melhorou 0.0027856486           -0.02999855            0.0004821000
Piorou   0.0001967714            0.01450743           -0.0001672875
         pop_esgot_interaction pop_residuo_interaction   log_pop22
Melhorou          1.184524e-08           -6.462737e-08 -0.10068020
Piorou           -1.134238e-08            1.293541e-07  0.01716738

Std. Errors:
          (Intercept)     temp_med     umid_med   precip_tot     thr_temp
Melhorou 4.141334e-10 9.280999e-09 3.094967e-08 2.241469e-07 1.129957e-07
Piorou   4.020812e-10 8.065173e-09 2.962038e-08 2.112075e-07 8.594119e-08
             thr_umid     thr_prec thr_temp_umid tipo_regiaonao metropolitana
Melhorou 1.304388e-07 2.848525e-09  9.475846e-08                 3.801490e-10
Piorou   1.247532e-07 3.411142e-09  6.858141e-08                 3.759381e-10
             altitude biomacaatinga biomacerrado biomamata atlantica
Melhorou 2.149590e-07  1.193364e-10 1.074908e-10        3.062517e-10
Piorou   2.212172e-07  1.235323e-10 6.602613e-11        4.081079e-10
          biomapampa biomapantanal     koppenAm     koppenAs     koppenAw
Melhorou 6.87168e-12  7.345530e-17 5.019797e-11 7.820668e-11 1.624605e-10
Piorou   2.80783e-11  9.469289e-13 3.211464e-11 8.906247e-11 8.737272e-11
            koppenBSh    koppenCfa    koppenCfb    koppenCwa    koppenCwb
Melhorou 4.276865e-11 6.178199e-11 5.598177e-11 5.348181e-11 7.317286e-11
Piorou   4.855246e-11 2.803009e-10 6.973616e-11 4.410017e-11 3.149062e-11
                pop22   prop_esgot prop_residuo temp_umid_interaction
Melhorou 6.460023e-06 2.006160e-08 3.530696e-08          6.916548e-07
Piorou   6.346255e-06 2.528906e-08 3.790961e-08          5.908872e-07
         temp_precip_interaction pop_esgot_interaction pop_residuo_interaction
Melhorou            5.037391e-06          4.257420e-08            8.440791e-08
Piorou              4.220162e-06          2.022648e-08            7.093737e-08
            log_pop22
Melhorou 3.448378e-09
Piorou   3.390993e-09

Residual Deviance: 9090.819 
AIC: 9214.819 </code></pre>
</div>
</div>
</section>
<section id="avaliação-do-ajuste-do-modelo-1" class="level2">
<h2 class="anchored" data-anchor-id="avaliação-do-ajuste-do-modelo-1">5. Avaliação do ajuste do modelo</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Pseudo R²</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a><span class="fu">pR2</span>(multinom_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>fitting null model for pseudo-r2
# weights:  6 (2 variable)
initial  value 6119.270448 
final  value 4878.405761 
converged</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>          llh       llhNull            G2      McFadden          r2ML 
-4545.4096914 -4878.4057608   665.9921387     0.0682592     0.1126961 
         r2CU 
    0.1363507 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Teste de razão de verossimilhança</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lrtest</span>(multinom_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># weights:  6 (2 variable)
initial  value 6119.270448 
final  value 4878.405761 
converged</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Likelihood ratio test

Model 1: Transition ~ temp_med + umid_med + precip_tot + thr_temp + thr_umid + 
    thr_prec + thr_temp_umid + tipo_regiao + altitude + bioma + 
    koppen + pop22 + prop_esgot + prop_residuo + temp_umid_interaction + 
    temp_precip_interaction + pop_esgot_interaction + pop_residuo_interaction + 
    log_pop22
Model 2: Transition ~ 1
  #Df  LogLik  Df  Chisq Pr(&gt;Chisq)    
1  62 -4545.4                          
2   2 -4878.4 -60 665.99  &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
<section id="seleção-de-variáveis-1" class="level2">
<h2 class="anchored" data-anchor-id="seleção-de-variáveis-1">6. Seleção de variáveis</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Seleção stepwise</span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>step_model <span class="ot">&lt;-</span> <span class="fu">step</span>(multinom_model, <span class="at">direction =</span> <span class="st">"both"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=9214.82
Transition ~ temp_med + umid_med + precip_tot + thr_temp + thr_umid + 
    thr_prec + thr_temp_umid + tipo_regiao + altitude + bioma + 
    koppen + pop22 + prop_esgot + prop_residuo + temp_umid_interaction + 
    temp_precip_interaction + pop_esgot_interaction + pop_residuo_interaction + 
    log_pop22

trying - temp_med 
# weights:  93 (60 variable)
initial  value 6119.270448 
iter  10 value 5107.312027
iter  20 value 5007.661442
iter  30 value 4963.761792
iter  40 value 4770.453294
iter  50 value 4665.529138
iter  60 value 4649.364376
iter  70 value 4625.193696
iter  80 value 4582.249106
iter  90 value 4572.408610
iter 100 value 4567.732899
final  value 4567.732899 
stopped after 100 iterations
trying - umid_med 
# weights:  93 (60 variable)
initial  value 6119.270448 
iter  10 value 5107.449322
iter  20 value 5008.401553
iter  30 value 4956.090638
iter  40 value 4836.789356
iter  50 value 4695.752392
iter  60 value 4685.949589
iter  70 value 4638.840285
iter  80 value 4617.160866
iter  90 value 4610.572761
iter 100 value 4594.504748
final  value 4594.504748 
stopped after 100 iterations
trying - precip_tot 
# weights:  93 (60 variable)
initial  value 6119.270448 
iter  10 value 5109.422155
iter  20 value 5017.517251
iter  30 value 4960.200082
iter  40 value 4670.640389
iter  50 value 4641.672332
iter  60 value 4625.953720
iter  70 value 4603.297696
iter  80 value 4593.598203
iter  90 value 4589.493357
iter 100 value 4584.902039
final  value 4584.902039 
stopped after 100 iterations
trying - thr_temp 
# weights:  93 (60 variable)
initial  value 6119.270448 
iter  10 value 5114.443736
iter  20 value 5020.567744
iter  30 value 4957.759797
iter  40 value 4753.794430
iter  40 value 4753.794430
iter  50 value 4672.029486
iter  60 value 4653.265922
iter  70 value 4612.091134
iter  80 value 4582.005850
iter  90 value 4574.739975
iter 100 value 4551.664590
final  value 4551.664590 
stopped after 100 iterations
trying - thr_umid 
# weights:  93 (60 variable)
initial  value 6119.270448 
iter  10 value 5108.936974
iter  20 value 5006.288925
iter  30 value 4949.490320
iter  40 value 4704.444009
iter  50 value 4649.624864
iter  60 value 4626.065918
iter  70 value 4609.909715
iter  80 value 4593.725621
iter  90 value 4592.326141
iter 100 value 4587.764622
final  value 4587.764622 
stopped after 100 iterations
trying - thr_prec 
# weights:  93 (60 variable)
initial  value 6119.270448 
iter  10 value 5107.286423
iter  20 value 5007.799327
iter  30 value 4952.013780
iter  40 value 4750.320938
iter  50 value 4718.108710
iter  60 value 4693.564396
iter  70 value 4612.495715
iter  80 value 4605.933759
iter  90 value 4598.967754
iter 100 value 4594.741781
final  value 4594.741781 
stopped after 100 iterations
trying - thr_temp_umid 
# weights:  93 (60 variable)
initial  value 6119.270448 
iter  10 value 5110.177250
iter  20 value 5008.173521
iter  30 value 4951.248253
iter  40 value 4749.873958
iter  50 value 4705.437569
iter  60 value 4688.534085
iter  70 value 4636.870616
iter  80 value 4625.933145
iter  90 value 4611.855358
iter 100 value 4594.047111
final  value 4594.047111 
stopped after 100 iterations
trying - tipo_regiao 
# weights:  93 (60 variable)
initial  value 6119.270448 
iter  10 value 5107.282896
iter  20 value 5007.720560
iter  30 value 4964.813928
iter  40 value 4744.618734
iter  50 value 4703.962903
iter  60 value 4681.744782
iter  70 value 4649.360129
iter  80 value 4610.795710
iter  90 value 4591.446767
iter 100 value 4590.724459
final  value 4590.724459 
stopped after 100 iterations
trying - altitude 
# weights:  93 (60 variable)
initial  value 6119.270448 
iter  10 value 5153.509564
iter  20 value 5068.597982
iter  30 value 4987.699282
iter  40 value 4750.054259
iter  50 value 4732.566875
iter  60 value 4704.871461
iter  70 value 4633.860526
iter  80 value 4622.806994
iter  90 value 4609.197053
iter 100 value 4601.168388
final  value 4601.168388 
stopped after 100 iterations
trying - bioma 
# weights:  81 (52 variable)
initial  value 6119.270448 
iter  10 value 5107.282929
iter  20 value 5007.722479
iter  30 value 4972.099864
iter  40 value 4815.587406
iter  50 value 4672.784817
iter  60 value 4655.450295
iter  70 value 4622.172203
iter  80 value 4588.847896
iter  90 value 4577.845088
iter 100 value 4572.867009
final  value 4572.867009 
stopped after 100 iterations
trying - koppen 
# weights:  72 (46 variable)
initial  value 6119.270448 
iter  10 value 5107.283030
iter  20 value 5007.859794
iter  30 value 4976.730534
iter  40 value 4845.939485
iter  50 value 4767.665059
iter  60 value 4750.524964
iter  70 value 4707.015297
iter  80 value 4662.201130
iter  90 value 4593.043871
iter 100 value 4591.230506
final  value 4591.230506 
stopped after 100 iterations
trying - pop22 
# weights:  93 (60 variable)
initial  value 6119.270448 
iter  10 value 5216.952521
iter  20 value 5066.313254
iter  30 value 4908.716014
iter  40 value 4680.360377
iter  50 value 4652.446825
iter  60 value 4642.935417
iter  70 value 4609.126206
iter  80 value 4581.970995
iter  90 value 4578.835069
iter 100 value 4578.676766
final  value 4578.676766 
stopped after 100 iterations
trying - prop_esgot 
# weights:  93 (60 variable)
initial  value 6119.270448 
iter  10 value 5107.495055
iter  20 value 5006.535554
iter  30 value 4946.466958
iter  40 value 4682.974629
iter  50 value 4663.669091
iter  60 value 4646.798014
iter  70 value 4606.638557
iter  80 value 4588.257144
iter  90 value 4587.541179
iter 100 value 4586.864029
final  value 4586.864029 
stopped after 100 iterations
trying - prop_residuo 
# weights:  93 (60 variable)
initial  value 6119.270448 
iter  10 value 5107.623224
iter  20 value 5008.427101
iter  30 value 4947.265095
iter  40 value 4759.230374
iter  50 value 4668.460977
iter  60 value 4650.856115
iter  70 value 4607.036934
iter  80 value 4601.865161
iter  90 value 4597.056172
iter 100 value 4588.895566
final  value 4588.895566 
stopped after 100 iterations
trying - temp_umid_interaction 
# weights:  93 (60 variable)
initial  value 6119.270448 
iter  10 value 5146.293287
iter  20 value 5044.448165
iter  30 value 4987.035983
iter  40 value 4733.512795
iter  50 value 4685.636740
iter  60 value 4655.179473
iter  70 value 4631.745898
iter  80 value 4605.182144
iter  90 value 4599.325847
iter 100 value 4593.626141
final  value 4593.626141 
stopped after 100 iterations
trying - temp_precip_interaction 
# weights:  93 (60 variable)
initial  value 6119.270448 
iter  10 value 5011.887998
iter  20 value 4919.523893
iter  30 value 4867.992178
iter  40 value 4668.450993
iter  50 value 4622.931404
iter  60 value 4615.253288
iter  70 value 4598.416090
iter  80 value 4579.650853
iter  90 value 4571.769674
iter 100 value 4551.763978
final  value 4551.763978 
stopped after 100 iterations
trying - pop_esgot_interaction 
# weights:  93 (60 variable)
initial  value 6119.270448 
iter  10 value 5095.623208
iter  20 value 5014.317322
iter  30 value 4954.050888
iter  40 value 4857.481780
iter  50 value 4680.553462
iter  60 value 4656.736143
iter  70 value 4616.275723
iter  80 value 4579.161845
iter  90 value 4573.412160
iter 100 value 4549.238775
final  value 4549.238775 
stopped after 100 iterations
trying - pop_residuo_interaction 
# weights:  93 (60 variable)
initial  value 6119.270448 
iter  10 value 5105.782677
iter  20 value 4954.536127
iter  30 value 4863.382779
iter  40 value 4653.472380
iter  50 value 4581.728451
iter  60 value 4571.122719
iter  70 value 4547.594692
final  value 4546.705189 
converged
trying - log_pop22 
# weights:  93 (60 variable)
initial  value 6119.270448 
iter  10 value 5107.286574
iter  20 value 5007.839608
iter  30 value 4954.764267
iter  40 value 4703.586728
iter  50 value 4658.877681
iter  60 value 4651.025424
iter  70 value 4636.603332
iter  80 value 4604.381387
iter  90 value 4602.081705
iter 100 value 4587.323789
final  value 4587.323789 
stopped after 100 iterations
                          Df      AIC
- pop_residuo_interaction 60 9213.410
&lt;none&gt;                    62 9214.819
- pop_esgot_interaction   60 9218.478
- thr_temp                60 9223.329
- temp_precip_interaction 60 9223.528
- bioma                   52 9249.734
- temp_med                60 9255.466
- koppen                  46 9274.461
- pop22                   60 9277.354
- precip_tot              60 9289.804
- prop_esgot              60 9293.728
- log_pop22               60 9294.648
- thr_umid                60 9295.529
- prop_residuo            60 9297.791
- tipo_regiao             60 9301.449
- temp_umid_interaction   60 9307.252
- thr_temp_umid           60 9308.094
- umid_med                60 9309.009
- thr_prec                60 9309.484
- altitude                60 9322.337
# weights:  93 (60 variable)
initial  value 6119.270448 
iter  10 value 5105.782677
iter  20 value 4954.536127
iter  30 value 4863.382779
iter  40 value 4653.472380
iter  50 value 4581.728451
iter  60 value 4571.122719
iter  70 value 4547.594692
final  value 4546.705189 
converged

Step:  AIC=9213.41
Transition ~ temp_med + umid_med + precip_tot + thr_temp + thr_umid + 
    thr_prec + thr_temp_umid + tipo_regiao + altitude + bioma + 
    koppen + pop22 + prop_esgot + prop_residuo + temp_umid_interaction + 
    temp_precip_interaction + pop_esgot_interaction + log_pop22

trying - temp_med 
# weights:  90 (58 variable)
initial  value 6119.270448 
iter  10 value 5105.798157
iter  20 value 4954.509626
iter  30 value 4842.830368
iter  40 value 4658.089616
iter  50 value 4620.594589
iter  60 value 4570.034619
iter  70 value 4568.580783
iter  80 value 4568.578014
final  value 4568.574536 
converged
trying - umid_med 
# weights:  90 (58 variable)
initial  value 6119.270448 
iter  10 value 5106.092710
iter  20 value 4955.910017
iter  30 value 4810.431577
iter  40 value 4615.811992
iter  50 value 4577.000601
iter  60 value 4568.795606
iter  70 value 4567.745353
iter  80 value 4567.729532
final  value 4567.729169 
converged
trying - precip_tot 
# weights:  90 (58 variable)
initial  value 6119.270448 
iter  10 value 5118.636447
iter  20 value 4981.793213
iter  30 value 4850.278340
iter  40 value 4621.999691
iter  50 value 4577.700241
iter  60 value 4567.958223
iter  70 value 4551.326171
final  value 4550.737759 
converged
trying - thr_temp 
# weights:  90 (58 variable)
initial  value 6119.270448 
iter  10 value 5114.097574
iter  20 value 4987.925641
iter  30 value 4851.433348
iter  40 value 4617.805716
iter  50 value 4579.759451
iter  60 value 4561.951107
iter  70 value 4547.966692
iter  80 value 4547.356371
iter  80 value 4547.356368
iter  80 value 4547.356368
final  value 4547.356368 
converged
trying - thr_umid 
# weights:  90 (58 variable)
initial  value 6119.270448 
iter  10 value 5110.291045
iter  20 value 4967.953911
iter  30 value 4830.513691
iter  40 value 4637.028202
iter  50 value 4581.422059
iter  60 value 4567.057240
iter  70 value 4548.023118
iter  80 value 4547.260846
final  value 4547.260664 
converged
trying - thr_prec 
# weights:  90 (58 variable)
initial  value 6119.270448 
iter  10 value 5105.810996
iter  20 value 4954.722457
iter  30 value 4849.374918
iter  40 value 4683.775855
iter  50 value 4667.447094
iter  50 value 4667.447094
iter  60 value 4598.304590
iter  70 value 4594.147216
iter  80 value 4585.427487
iter  90 value 4578.204601
iter 100 value 4565.972917
final  value 4565.972917 
stopped after 100 iterations
trying - thr_temp_umid 
# weights:  90 (58 variable)
initial  value 6119.270448 
iter  10 value 5117.232115
iter  20 value 4971.727820
iter  30 value 4823.368180
iter  40 value 4652.496193
iter  50 value 4588.885420
iter  60 value 4568.587108
iter  70 value 4548.552559
final  value 4547.940982 
converged
trying - tipo_regiao 
# weights:  90 (58 variable)
initial  value 6119.270448 
iter  10 value 5105.782752
iter  20 value 4954.536942
iter  30 value 4862.870374
iter  40 value 4651.845265
iter  50 value 4585.614536
iter  60 value 4569.425218
iter  70 value 4547.700334
final  value 4546.860641 
converged
trying - altitude 
# weights:  90 (58 variable)
initial  value 6119.270448 
iter  10 value 5077.646734
iter  20 value 4978.476225
iter  30 value 4773.572034
iter  40 value 4617.549106
iter  50 value 4585.730473
iter  60 value 4571.654597
iter  70 value 4556.836365
iter  80 value 4556.692424
iter  80 value 4556.692412
iter  80 value 4556.692412
final  value 4556.692412 
converged
trying - bioma 
# weights:  78 (50 variable)
initial  value 6119.270448 
iter  10 value 5105.783451
iter  20 value 4954.555124
iter  30 value 4875.215746
iter  40 value 4633.168327
iter  50 value 4587.560512
iter  60 value 4560.011986
iter  70 value 4558.238865
final  value 4558.155077 
converged
trying - koppen 
# weights:  69 (44 variable)
initial  value 6119.270448 
iter  10 value 5105.784607
iter  20 value 4954.872381
iter  30 value 4865.593537
iter  40 value 4710.975494
iter  50 value 4606.562746
iter  60 value 4592.836059
final  value 4592.308507 
converged
trying - pop22 
# weights:  90 (58 variable)
initial  value 6119.270448 
iter  10 value 5099.184041
iter  20 value 5059.717717
iter  30 value 4984.212917
iter  40 value 4823.923394
iter  50 value 4672.137598
iter  60 value 4661.790457
iter  70 value 4613.921830
iter  80 value 4590.138993
iter  90 value 4588.584012
iter 100 value 4584.004097
final  value 4584.004097 
stopped after 100 iterations
trying - prop_esgot 
# weights:  90 (58 variable)
initial  value 6119.270448 
iter  10 value 5109.145294
iter  20 value 4962.705666
iter  30 value 4817.133547
iter  40 value 4636.441710
iter  50 value 4583.513085
iter  60 value 4567.588314
iter  70 value 4549.261239
final  value 4548.698388 
converged
trying - prop_residuo 
# weights:  90 (58 variable)
initial  value 6119.270448 
iter  10 value 5108.842859
iter  20 value 4966.458415
iter  30 value 4815.123792
iter  40 value 4615.772787
iter  50 value 4579.102127
iter  60 value 4567.021822
iter  70 value 4547.435877
final  value 4547.122922 
converged
trying - temp_umid_interaction 
# weights:  90 (58 variable)
initial  value 6119.270448 
iter  10 value 5072.461985
iter  20 value 4956.864001
iter  30 value 4823.355816
iter  40 value 4708.412553
iter  50 value 4629.873710
iter  60 value 4613.708695
iter  70 value 4601.326094
iter  80 value 4585.219077
iter  90 value 4573.747231
iter 100 value 4567.085792
final  value 4567.085792 
stopped after 100 iterations
trying - temp_precip_interaction 
# weights:  90 (58 variable)
initial  value 6119.270448 
iter  10 value 5215.572518
iter  20 value 5137.650153
iter  30 value 4893.821412
iter  40 value 4600.722378
iter  50 value 4577.296997
iter  60 value 4561.894167
iter  70 value 4551.516332
final  value 4551.486130 
converged
trying - pop_esgot_interaction 
# weights:  90 (58 variable)
initial  value 6119.270448 
iter  10 value 4869.230198
iter  20 value 4813.966036
iter  30 value 4756.023666
iter  40 value 4599.729933
iter  50 value 4575.735205
iter  60 value 4549.613984
iter  70 value 4546.727461
final  value 4546.726863 
converged
trying - log_pop22 
# weights:  90 (58 variable)
initial  value 6119.270448 
iter  10 value 5105.792060
iter  20 value 4954.735344
iter  30 value 4832.893670
iter  40 value 4630.637252
iter  50 value 4581.044849
iter  60 value 4566.878630
iter  70 value 4547.936579
final  value 4547.625359 
converged
trying + pop_residuo_interaction 
# weights:  96 (62 variable)
initial  value 6119.270448 
iter  10 value 5107.282832
iter  20 value 5007.716419
iter  30 value 4964.211890
iter  40 value 4770.128902
iter  50 value 4694.889238
iter  60 value 4681.463549
iter  70 value 4658.902609
iter  80 value 4605.926710
iter  90 value 4600.745095
iter 100 value 4593.199727
final  value 4593.199727 
stopped after 100 iterations
                           Df      AIC
- pop_esgot_interaction    58 9209.454
- tipo_regiao              58 9209.721
- prop_residuo             58 9210.246
- thr_umid                 58 9210.521
- thr_temp                 58 9210.713
- log_pop22                58 9211.251
- thr_temp_umid            58 9211.882
- prop_esgot               58 9213.397
&lt;none&gt;                     60 9213.410
- bioma                    50 9216.310
- precip_tot               58 9217.476
- temp_precip_interaction  58 9218.972
- altitude                 58 9229.385
- thr_prec                 58 9247.946
- temp_umid_interaction    58 9250.172
- umid_med                 58 9251.458
- temp_med                 58 9253.149
- koppen                   44 9272.617
- pop22                    58 9284.008
+ +pop_residuo_interaction 62 9310.399
# weights:  90 (58 variable)
initial  value 6119.270448 
iter  10 value 4869.230198
iter  20 value 4813.966036
iter  30 value 4756.023666
iter  40 value 4599.729933
iter  50 value 4575.735205
iter  60 value 4549.613984
iter  70 value 4546.727461
final  value 4546.726863 
converged

Step:  AIC=9209.45
Transition ~ temp_med + umid_med + precip_tot + thr_temp + thr_umid + 
    thr_prec + thr_temp_umid + tipo_regiao + altitude + bioma + 
    koppen + pop22 + prop_esgot + prop_residuo + temp_umid_interaction + 
    temp_precip_interaction + log_pop22

trying - temp_med 
# weights:  87 (56 variable)
initial  value 6119.270448 
iter  10 value 4869.186597
iter  20 value 4813.875063
iter  30 value 4759.537473
iter  40 value 4607.530755
iter  50 value 4576.081010
iter  60 value 4568.668224
iter  70 value 4568.590025
final  value 4568.580373 
converged
trying - umid_med 
# weights:  87 (56 variable)
initial  value 6119.270448 
iter  10 value 4869.093981
iter  20 value 4817.987408
iter  30 value 4723.205776
iter  40 value 4598.519808
iter  50 value 4573.868354
iter  60 value 4567.798543
iter  70 value 4567.744425
final  value 4567.736096 
converged
trying - precip_tot 
# weights:  87 (56 variable)
initial  value 6119.270448 
iter  10 value 4883.868056
iter  20 value 4828.898111
iter  30 value 4701.745690
iter  40 value 4589.827959
iter  50 value 4575.224603
iter  60 value 4552.024788
iter  70 value 4550.808588
final  value 4550.808471 
converged
trying - thr_temp 
# weights:  87 (56 variable)
initial  value 6119.270448 
iter  10 value 4850.706085
iter  20 value 4819.222245
iter  30 value 4739.898923
iter  40 value 4604.639122
iter  50 value 4576.532412
iter  60 value 4548.511285
iter  70 value 4547.381518
iter  70 value 4547.381516
iter  70 value 4547.381516
final  value 4547.381516 
converged
trying - thr_umid 
# weights:  87 (56 variable)
initial  value 6119.270448 
iter  10 value 4862.882122
iter  20 value 4811.898631
iter  30 value 4719.418665
iter  40 value 4598.592448
iter  50 value 4575.641139
iter  60 value 4548.571882
iter  70 value 4547.283089
iter  70 value 4547.283079
iter  70 value 4547.283079
final  value 4547.283079 
converged
trying - thr_prec 
# weights:  87 (56 variable)
initial  value 6119.270448 
iter  10 value 4869.273402
iter  20 value 4814.480604
iter  30 value 4721.266095
iter  40 value 4593.870846
iter  50 value 4578.283998
iter  60 value 4549.976343
iter  70 value 4548.644543
iter  70 value 4548.644528
iter  70 value 4548.644528
final  value 4548.644528 
converged
trying - thr_temp_umid 
# weights:  87 (56 variable)
initial  value 6119.270448 
iter  10 value 4885.516411
iter  20 value 4812.765298
iter  30 value 4749.628231
iter  40 value 4599.691754
iter  50 value 4576.885230
iter  60 value 4549.103012
iter  70 value 4547.958453
iter  70 value 4547.958444
iter  70 value 4547.958444
final  value 4547.958444 
converged
trying - tipo_regiao 
# weights:  87 (56 variable)
initial  value 6119.270448 
iter  10 value 4869.230411
iter  20 value 4814.029123
iter  30 value 4761.369860
iter  40 value 4597.919773
iter  50 value 4575.875041
iter  60 value 4548.078738
iter  70 value 4546.879140
final  value 4546.878865 
converged
trying - altitude 
# weights:  87 (56 variable)
initial  value 6119.270448 
iter  10 value 4895.029308
iter  20 value 4860.671108
iter  30 value 4693.286624
iter  40 value 4598.072486
iter  50 value 4583.508120
iter  60 value 4558.057688
final  value 4556.739061 
converged
trying - bioma 
# weights:  75 (48 variable)
initial  value 6119.270448 
iter  10 value 4869.230998
iter  20 value 4814.248665
iter  30 value 4761.919742
iter  40 value 4597.129338
iter  50 value 4576.960017
iter  60 value 4558.481651
final  value 4558.178159 
converged
trying - koppen 
# weights:  66 (42 variable)
initial  value 6119.270448 
iter  10 value 4869.234621
iter  20 value 4816.355947
iter  30 value 4762.435442
iter  40 value 4640.741229
iter  50 value 4593.624104
final  value 4592.368045 
converged
trying - pop22 
# weights:  87 (56 variable)
initial  value 6119.270448 
iter  10 value 5539.375071
iter  20 value 5464.891930
iter  30 value 5131.476241
iter  40 value 4685.060156
iter  50 value 4579.960850
iter  60 value 4557.689514
iter  70 value 4549.593052
final  value 4549.582362 
converged
trying - prop_esgot 
# weights:  87 (56 variable)
initial  value 6119.270448 
iter  10 value 4870.201572
iter  20 value 4802.978459
iter  30 value 4690.765040
iter  40 value 4590.846761
iter  50 value 4575.740215
iter  60 value 4550.198266
iter  70 value 4549.072216
final  value 4549.072136 
converged
trying - prop_residuo 
# weights:  87 (56 variable)
initial  value 6119.270448 
iter  10 value 4871.899839
iter  20 value 4809.678521
iter  30 value 4703.168483
iter  40 value 4593.354861
iter  50 value 4574.995054
iter  60 value 4548.307590
final  value 4547.155765 
converged
trying - temp_umid_interaction 
# weights:  87 (56 variable)
initial  value 6119.270448 
iter  10 value 4944.881701
iter  20 value 4909.649918
iter  30 value 4759.572885
iter  40 value 4606.600460
iter  50 value 4573.818725
iter  60 value 4566.174360
iter  70 value 4566.117202
final  value 4566.108314 
converged
trying - temp_precip_interaction 
# weights:  87 (56 variable)
initial  value 6119.270448 
iter  10 value 5168.653400
iter  20 value 5076.363804
iter  30 value 4765.107583
iter  40 value 4601.062371
iter  50 value 4576.152980
iter  60 value 4553.319303
iter  70 value 4551.601526
final  value 4551.560433 
converged
trying - log_pop22 
# weights:  87 (56 variable)
initial  value 6119.270448 
iter  10 value 4869.225651
iter  20 value 4814.718115
iter  30 value 4712.478327
iter  40 value 4590.196775
iter  50 value 4577.190953
iter  60 value 4549.285927
iter  70 value 4547.662306
final  value 4547.662110 
converged
trying + pop_esgot_interaction 
# weights:  93 (60 variable)
initial  value 6119.270448 
iter  10 value 5105.782679
iter  20 value 4954.538821
iter  30 value 4867.378970
iter  40 value 4667.120194
iter  50 value 4594.866933
iter  60 value 4569.563313
iter  70 value 4547.626755
final  value 4546.706920 
converged
trying + pop_residuo_interaction 
# weights:  93 (60 variable)
initial  value 6119.270448 
iter  10 value 5095.623204
iter  20 value 5014.315052
iter  30 value 4951.266798
iter  40 value 4807.696545
iter  50 value 4664.948625
iter  60 value 4626.524674
iter  70 value 4620.768709
iter  80 value 4594.509052
iter  90 value 4576.014744
iter 100 value 4567.286596
final  value 4567.286596 
stopped after 100 iterations
                           Df      AIC
- tipo_regiao              56 9205.758
- prop_residuo             56 9206.312
- thr_umid                 56 9206.566
- thr_temp                 56 9206.763
- log_pop22                56 9207.324
- thr_temp_umid            56 9207.917
- thr_prec                 56 9209.289
&lt;none&gt;                     58 9209.454
- prop_esgot               56 9210.144
- pop22                    56 9211.165
- bioma                    48 9212.356
+ +pop_esgot_interaction   60 9213.414
- precip_tot               56 9213.617
- temp_precip_interaction  56 9215.121
- altitude                 56 9225.478
- temp_umid_interaction    56 9244.217
- umid_med                 56 9247.472
- temp_med                 56 9249.161
+ +pop_residuo_interaction 60 9254.573
- koppen                   42 9268.736
# weights:  87 (56 variable)
initial  value 6119.270448 
iter  10 value 4869.230411
iter  20 value 4814.029123
iter  30 value 4761.369860
iter  40 value 4597.919773
iter  50 value 4575.875041
iter  60 value 4548.078738
iter  70 value 4546.879140
final  value 4546.878865 
converged

Step:  AIC=9205.76
Transition ~ temp_med + umid_med + precip_tot + thr_temp + thr_umid + 
    thr_prec + thr_temp_umid + altitude + bioma + koppen + pop22 + 
    prop_esgot + prop_residuo + temp_umid_interaction + temp_precip_interaction + 
    log_pop22

trying - temp_med 
# weights:  84 (54 variable)
initial  value 6119.270448 
iter  10 value 4869.186810
iter  20 value 4813.939311
iter  30 value 4760.603989
iter  40 value 4604.871332
iter  50 value 4573.831227
iter  60 value 4568.732168
iter  70 value 4568.686912
final  value 4568.684665 
converged
trying - umid_med 
# weights:  84 (54 variable)
initial  value 6119.270448 
iter  10 value 4869.094197
iter  20 value 4818.047027
iter  30 value 4715.509940
iter  40 value 4597.778807
iter  50 value 4574.042026
iter  60 value 4567.918062
iter  70 value 4567.870671
final  value 4567.866023 
converged
trying - precip_tot 
# weights:  84 (54 variable)
initial  value 6119.270448 
iter  10 value 4883.868379
iter  20 value 4828.992852
iter  30 value 4700.981615
iter  40 value 4590.144653
iter  50 value 4574.560839
iter  60 value 4551.739313
final  value 4550.993158 
converged
trying - thr_temp 
# weights:  84 (54 variable)
initial  value 6119.270448 
iter  10 value 4850.706336
iter  20 value 4819.162732
iter  30 value 4741.698022
iter  40 value 4609.288629
iter  50 value 4575.259868
iter  60 value 4548.399241
final  value 4547.520880 
converged
trying - thr_umid 
# weights:  84 (54 variable)
initial  value 6119.270448 
iter  10 value 4862.882370
iter  20 value 4811.967748
iter  30 value 4717.172523
iter  40 value 4596.958872
iter  50 value 4575.551171
iter  60 value 4548.301208
final  value 4547.428831 
converged
trying - thr_prec 
# weights:  84 (54 variable)
initial  value 6119.270448 
iter  10 value 4869.273615
iter  20 value 4814.546655
iter  30 value 4718.966721
iter  40 value 4594.276362
iter  50 value 4577.827877
iter  60 value 4549.890390
final  value 4548.806095 
converged
trying - thr_temp_umid 
# weights:  84 (54 variable)
initial  value 6119.270448 
iter  10 value 4885.516683
iter  20 value 4812.846050
iter  30 value 4745.482584
iter  40 value 4600.231311
iter  50 value 4575.486988
iter  60 value 4548.894543
final  value 4548.093738 
converged
trying - altitude 
# weights:  84 (54 variable)
initial  value 6119.270448 
iter  10 value 4895.028971
iter  20 value 4860.717595
iter  30 value 4690.000508
iter  40 value 4595.226498
iter  50 value 4581.966926
iter  60 value 4558.126616
final  value 4556.912781 
converged
trying - bioma 
# weights:  72 (46 variable)
initial  value 6119.270448 
iter  10 value 4869.231211
iter  20 value 4814.311704
iter  30 value 4761.228859
iter  40 value 4601.819417
iter  50 value 4575.528217
iter  60 value 4558.590931
final  value 4558.449473 
converged
trying - koppen 
# weights:  63 (40 variable)
initial  value 6119.270448 
iter  10 value 4869.234833
iter  20 value 4816.411912
iter  30 value 4758.812392
iter  40 value 4633.981008
iter  50 value 4593.213870
final  value 4592.444578 
converged
trying - pop22 
# weights:  84 (54 variable)
initial  value 6119.270448 
iter  10 value 5539.379773
iter  20 value 5465.093356
iter  30 value 5093.796808
iter  40 value 4699.577765
iter  50 value 4579.697782
iter  60 value 4552.934838
iter  70 value 4550.126623
final  value 4550.113724 
converged
trying - prop_esgot 
# weights:  84 (54 variable)
initial  value 6119.270448 
iter  10 value 4870.201793
iter  20 value 4803.116319
iter  30 value 4688.068066
iter  40 value 4589.125463
iter  50 value 4574.271116
iter  60 value 4550.113023
final  value 4549.187697 
converged
trying - prop_residuo 
# weights:  84 (54 variable)
initial  value 6119.270448 
iter  10 value 4871.900061
iter  20 value 4809.808052
iter  30 value 4700.964875
iter  40 value 4593.031045
iter  50 value 4573.729540
iter  60 value 4548.177220
final  value 4547.288200 
converged
trying - temp_umid_interaction 
# weights:  84 (54 variable)
initial  value 6119.270448 
iter  10 value 4944.881843
iter  20 value 4908.770952
iter  30 value 4757.711445
iter  40 value 4605.686288
iter  50 value 4573.124890
iter  60 value 4566.285556
iter  70 value 4566.242171
final  value 4566.238529 
converged
trying - temp_precip_interaction 
# weights:  84 (54 variable)
initial  value 6119.270448 
iter  10 value 5168.653316
iter  20 value 5076.587258
iter  30 value 4749.864120
iter  40 value 4600.765454
iter  50 value 4575.214305
iter  60 value 4552.593420
iter  70 value 4551.722158
final  value 4551.721601 
converged
trying - log_pop22 
# weights:  84 (54 variable)
initial  value 6119.270448 
iter  10 value 4869.225864
iter  20 value 4814.780532
iter  30 value 4711.341997
iter  40 value 4589.971873
iter  50 value 4576.107873
iter  60 value 4548.896253
final  value 4547.833128 
converged
trying + tipo_regiao 
# weights:  90 (58 variable)
initial  value 6119.270448 
iter  10 value 4869.230198
iter  20 value 4813.966037
iter  30 value 4756.023674
iter  40 value 4599.730117
iter  50 value 4575.735132
iter  60 value 4549.614561
iter  70 value 4546.727462
final  value 4546.726863 
converged
trying + pop_esgot_interaction 
# weights:  90 (58 variable)
initial  value 6119.270448 
iter  10 value 5105.782754
iter  20 value 4954.540350
iter  30 value 4867.670605
iter  40 value 4669.852336
iter  50 value 4604.716072
iter  60 value 4565.998922
iter  70 value 4547.555806
final  value 4546.862816 
converged
trying + pop_residuo_interaction 
# weights:  90 (58 variable)
initial  value 6119.270448 
iter  10 value 5095.623316
iter  20 value 5014.320316
iter  30 value 4948.149123
iter  40 value 4668.160971
iter  50 value 4580.118923
iter  60 value 4564.080742
iter  70 value 4546.067797
final  value 4545.709975 
converged
                           Df      AIC
- prop_residuo             54 9202.576
- thr_umid                 54 9202.858
- thr_temp                 54 9203.042
- log_pop22                54 9203.666
- thr_temp_umid            54 9204.187
- thr_prec                 54 9205.612
&lt;none&gt;                     56 9205.758
- prop_esgot               54 9206.375
+ +pop_residuo_interaction 58 9207.420
- pop22                    54 9208.227
- bioma                    46 9208.899
+ +tipo_regiao             58 9209.454
+ +pop_esgot_interaction   58 9209.726
- precip_tot               54 9209.986
- temp_precip_interaction  54 9211.443
- altitude                 54 9221.826
- temp_umid_interaction    54 9240.477
- umid_med                 54 9243.732
- temp_med                 54 9245.369
- koppen                   40 9264.889
# weights:  84 (54 variable)
initial  value 6119.270448 
iter  10 value 4871.900061
iter  20 value 4809.808052
iter  30 value 4700.964875
iter  40 value 4593.031045
iter  50 value 4573.729540
iter  60 value 4548.177220
final  value 4547.288200 
converged

Step:  AIC=9202.58
Transition ~ temp_med + umid_med + precip_tot + thr_temp + thr_umid + 
    thr_prec + thr_temp_umid + altitude + bioma + koppen + pop22 + 
    prop_esgot + temp_umid_interaction + temp_precip_interaction + 
    log_pop22

trying - temp_med 
# weights:  81 (52 variable)
initial  value 6119.270448 
iter  10 value 4871.857110
iter  20 value 4809.333271
iter  30 value 4692.273427
iter  40 value 4592.842123
iter  50 value 4572.920346
iter  60 value 4569.044583
iter  70 value 4569.023107
final  value 4569.022535 
converged
trying - umid_med 
# weights:  81 (52 variable)
initial  value 6119.270448 
iter  10 value 4871.797270
iter  20 value 4817.572237
iter  30 value 4673.612467
iter  40 value 4591.450648
iter  50 value 4573.090754
iter  60 value 4568.196708
iter  70 value 4568.170499
final  value 4568.169599 
converged
trying - precip_tot 
# weights:  81 (52 variable)
initial  value 6119.270448 
iter  10 value 4888.337460
iter  20 value 4818.784370
iter  30 value 4678.802158
iter  40 value 4584.770047
iter  50 value 4573.486914
iter  60 value 4551.896676
final  value 4551.314247 
converged
trying - thr_temp 
# weights:  81 (52 variable)
initial  value 6119.270448 
iter  10 value 4853.505042
iter  20 value 4809.731006
iter  30 value 4690.275077
iter  40 value 4591.673206
iter  50 value 4574.231105
iter  60 value 4548.599165
final  value 4547.938768 
converged
trying - thr_umid 
# weights:  81 (52 variable)
initial  value 6119.270448 
iter  10 value 4865.893478
iter  20 value 4796.520676
iter  30 value 4724.124154
iter  40 value 4602.516674
iter  50 value 4573.944135
iter  60 value 4548.628382
final  value 4547.885929 
converged
trying - thr_prec 
# weights:  81 (52 variable)
initial  value 6119.270448 
iter  10 value 4871.945322
iter  20 value 4809.304951
iter  30 value 4682.420662
iter  40 value 4587.168260
iter  50 value 4575.249326
iter  60 value 4549.828352
final  value 4548.965501 
converged
trying - thr_temp_umid 
# weights:  81 (52 variable)
initial  value 6119.270448 
iter  10 value 4888.973193
iter  20 value 4805.255564
iter  30 value 4701.978009
iter  40 value 4590.522168
iter  50 value 4574.193109
iter  60 value 4549.129936
final  value 4548.543882 
converged
trying - altitude 
# weights:  81 (52 variable)
initial  value 6119.270448 
iter  10 value 4886.274367
iter  20 value 4820.871334
iter  30 value 4649.657971
iter  40 value 4589.978325
iter  50 value 4582.149873
iter  60 value 4558.761741
final  value 4558.071079 
converged
trying - bioma 
# weights:  69 (44 variable)
initial  value 6119.270448 
iter  10 value 4871.900957
iter  20 value 4810.447536
iter  30 value 4689.035314
iter  40 value 4590.300983
iter  50 value 4561.777303
iter  60 value 4558.743112
final  value 4558.741875 
converged
trying - koppen 
# weights:  60 (38 variable)
initial  value 6119.270448 
iter  10 value 4871.904631
iter  20 value 4815.346142
iter  30 value 4732.365199
iter  40 value 4621.489529
iter  50 value 4592.861862
final  value 4592.718184 
converged
trying - pop22 
# weights:  81 (52 variable)
initial  value 6119.270448 
iter  10 value 5503.785817
iter  20 value 5382.052833
iter  30 value 5025.524656
iter  40 value 4647.782750
iter  50 value 4577.297763
iter  60 value 4551.588505
iter  70 value 4550.476561
final  value 4550.476133 
converged
trying - prop_esgot 
# weights:  81 (52 variable)
initial  value 6119.270448 
iter  10 value 4873.186460
iter  20 value 4789.063456
iter  30 value 4654.760008
iter  40 value 4585.373516
iter  50 value 4574.172235
iter  60 value 4550.806682
final  value 4549.989123 
converged
trying - temp_umid_interaction 
# weights:  81 (52 variable)
initial  value 6119.270448 
iter  10 value 4947.980276
iter  20 value 4897.147050
iter  30 value 4689.313956
iter  40 value 4596.219951
iter  50 value 4570.819575
iter  60 value 4566.569285
iter  70 value 4566.545202
final  value 4566.544518 
converged
trying - temp_precip_interaction 
# weights:  81 (52 variable)
initial  value 6119.270448 
iter  10 value 5183.168336
iter  20 value 5040.427997
iter  30 value 4766.949478
iter  40 value 4589.648623
iter  50 value 4574.586963
iter  60 value 4552.751141
final  value 4552.060312 
converged
trying - log_pop22 
# weights:  81 (52 variable)
initial  value 6119.270448 
iter  10 value 4871.896002
iter  20 value 4811.412439
iter  30 value 4668.545461
iter  40 value 4585.605292
iter  50 value 4574.809960
iter  60 value 4548.886556
final  value 4548.143895 
converged
trying + tipo_regiao 
# weights:  87 (56 variable)
initial  value 6119.270448 
iter  10 value 4871.899839
iter  20 value 4809.678560
iter  30 value 4703.175098
iter  40 value 4593.357679
iter  50 value 4574.994669
iter  60 value 4548.308023
final  value 4547.155765 
converged
trying + prop_residuo 
# weights:  87 (56 variable)
initial  value 6119.270448 
iter  10 value 4869.230411
iter  20 value 4814.029122
iter  30 value 4761.369648
iter  40 value 4597.919716
iter  50 value 4575.875076
iter  60 value 4548.078728
iter  70 value 4546.879140
final  value 4546.878865 
converged
trying + pop_esgot_interaction 
# weights:  87 (56 variable)
initial  value 6119.270448 
iter  10 value 5108.842935
iter  20 value 4966.460370
iter  30 value 4793.511646
iter  40 value 4618.420450
iter  50 value 4579.176960
iter  60 value 4556.465334
iter  70 value 4547.331327
final  value 4547.259341 
converged
trying + pop_residuo_interaction 
# weights:  87 (56 variable)
initial  value 6119.270448 
iter  10 value 5095.808476
iter  20 value 5021.505959
iter  30 value 4913.826037
iter  40 value 4818.838521
iter  50 value 4708.502388
iter  60 value 4688.153450
iter  70 value 4603.662794
iter  80 value 4577.161288
iter  90 value 4568.573807
iter 100 value 4547.049456
final  value 4547.049456 
stopped after 100 iterations
                           Df      AIC
- thr_umid                 52 9199.772
- thr_temp                 52 9199.878
- log_pop22                52 9200.288
- thr_temp_umid            52 9201.088
- thr_prec                 52 9201.931
&lt;none&gt;                     54 9202.576
- prop_esgot               52 9203.978
- pop22                    52 9204.952
- bioma                    44 9205.484
+ +prop_residuo            56 9205.758
+ +pop_residuo_interaction 56 9206.099
+ +tipo_regiao             56 9206.312
+ +pop_esgot_interaction   56 9206.519
- precip_tot               52 9206.628
- temp_precip_interaction  52 9208.121
- altitude                 52 9220.142
- temp_umid_interaction    52 9237.089
- umid_med                 52 9240.339
- temp_med                 52 9242.045
- koppen                   38 9261.436
# weights:  81 (52 variable)
initial  value 6119.270448 
iter  10 value 4865.893478
iter  20 value 4796.520676
iter  30 value 4724.124154
iter  40 value 4602.516674
iter  50 value 4573.944135
iter  60 value 4548.628382
final  value 4547.885929 
converged

Step:  AIC=9199.77
Transition ~ temp_med + umid_med + precip_tot + thr_temp + thr_prec + 
    thr_temp_umid + altitude + bioma + koppen + pop22 + prop_esgot + 
    temp_umid_interaction + temp_precip_interaction + log_pop22

trying - temp_med 
# weights:  78 (50 variable)
initial  value 6119.270448 
iter  10 value 4865.853945
iter  20 value 4799.435207
iter  30 value 4678.747157
iter  40 value 4583.630525
iter  50 value 4575.784241
iter  60 value 4575.544630
final  value 4575.541201 
converged
trying - umid_med 
# weights:  78 (50 variable)
initial  value 6119.270448 
iter  10 value 4865.914888
iter  20 value 4789.848997
iter  30 value 4657.616821
iter  40 value 4582.455202
iter  50 value 4576.253160
iter  60 value 4575.832065
final  value 4575.828142 
converged
trying - precip_tot 
# weights:  78 (50 variable)
initial  value 6119.270448 
iter  10 value 4870.561915
iter  20 value 4780.066105
iter  30 value 4662.928290
iter  40 value 4583.777670
iter  50 value 4569.850576
iter  60 value 4552.211208
final  value 4551.928869 
converged
trying - thr_temp 
# weights:  78 (50 variable)
initial  value 6119.270448 
iter  10 value 4850.786667
iter  20 value 4774.862909
iter  30 value 4663.482147
iter  40 value 4583.240011
iter  50 value 4569.006886
iter  60 value 4549.511056
final  value 4549.140058 
converged
trying - thr_prec 
# weights:  78 (50 variable)
initial  value 6119.270448 
iter  10 value 4865.947612
iter  20 value 4785.163071
iter  30 value 4682.638002
iter  40 value 4585.030223
iter  50 value 4570.593580
iter  60 value 4549.589626
final  value 4549.229278 
converged
trying - thr_temp_umid 
# weights:  78 (50 variable)
initial  value 6119.270448 
iter  10 value 4884.491036
iter  20 value 4781.806300
iter  30 value 4660.660993
iter  40 value 4583.915727
iter  50 value 4567.404718
iter  60 value 4557.748764
final  value 4557.657828 
converged
trying - altitude 
# weights:  78 (50 variable)
initial  value 6119.270448 
iter  10 value 4849.816822
iter  20 value 4773.267369
iter  30 value 4641.394135
iter  40 value 4592.641784
iter  50 value 4578.330106
iter  60 value 4559.242298
final  value 4558.977801 
converged
trying - bioma 
# weights:  66 (42 variable)
initial  value 6119.270448 
iter  10 value 4865.894636
iter  20 value 4798.314964
iter  30 value 4666.904444
iter  40 value 4590.528982
iter  50 value 4560.766404
final  value 4559.500802 
converged
trying - koppen 
# weights:  57 (36 variable)
initial  value 6119.270448 
iter  10 value 4865.898664
iter  20 value 4810.126057
iter  30 value 4693.845735
iter  40 value 4598.305819
iter  50 value 4593.624661
final  value 4593.624581 
converged
trying - pop22 
# weights:  78 (50 variable)
initial  value 6119.270448 
iter  10 value 5439.869705
iter  20 value 5269.340598
iter  30 value 4889.038249
iter  40 value 4635.770169
iter  50 value 4574.249125
iter  60 value 4552.000223
iter  70 value 4551.144559
iter  70 value 4551.144536
iter  70 value 4551.144536
final  value 4551.144536 
converged
trying - prop_esgot 
# weights:  78 (50 variable)
initial  value 6119.270448 
iter  10 value 4867.478585
iter  20 value 4771.325305
iter  30 value 4672.297091
iter  40 value 4585.321465
iter  50 value 4567.931913
iter  60 value 4550.988147
final  value 4550.705748 
converged
trying - temp_umid_interaction 
# weights:  78 (50 variable)
initial  value 6119.270448 
iter  10 value 4916.815747
iter  20 value 4862.876977
iter  30 value 4662.734522
iter  40 value 4583.184823
iter  50 value 4571.653722
iter  60 value 4570.953420
final  value 4570.948838 
converged
trying - temp_precip_interaction 
# weights:  78 (50 variable)
initial  value 6119.270448 
iter  10 value 5140.909209
iter  20 value 4948.135499
iter  30 value 4711.977644
iter  40 value 4596.326568
iter  50 value 4571.669450
iter  60 value 4552.858280
final  value 4552.714336 
converged
trying - log_pop22 
# weights:  78 (50 variable)
initial  value 6119.270448 
iter  10 value 4865.890190
iter  20 value 4780.973634
iter  30 value 4660.299549
iter  40 value 4585.701537
iter  50 value 4567.140064
iter  60 value 4549.028913
final  value 4548.729988 
converged
trying + thr_umid 
# weights:  84 (54 variable)
initial  value 6119.270448 
iter  10 value 4871.900061
iter  20 value 4809.808066
iter  30 value 4700.967411
iter  40 value 4593.033379
iter  50 value 4573.729324
iter  60 value 4548.177243
final  value 4547.288200 
converged
trying + tipo_regiao 
# weights:  84 (54 variable)
initial  value 6119.270448 
iter  10 value 4865.893218
iter  20 value 4796.355135
iter  30 value 4695.987047
iter  40 value 4596.471901
iter  50 value 4574.332064
iter  60 value 4548.589578
final  value 4547.758801 
converged
trying + prop_residuo 
# weights:  84 (54 variable)
initial  value 6119.270448 
iter  10 value 4862.882370
iter  20 value 4811.967746
iter  30 value 4717.171821
iter  40 value 4596.958519
iter  50 value 4575.550559
iter  60 value 4548.301215
final  value 4547.428831 
converged
trying + pop_esgot_interaction 
# weights:  84 (54 variable)
initial  value 6119.270448 
iter  10 value 5113.406626
iter  20 value 4965.488079
iter  30 value 4769.347021
iter  40 value 4605.107866
iter  50 value 4576.980624
iter  60 value 4549.412937
iter  70 value 4547.858115
final  value 4547.857959 
converged
trying + pop_residuo_interaction 
# weights:  84 (54 variable)
initial  value 6119.270448 
iter  10 value 5099.327354
iter  20 value 5013.758287
iter  30 value 4897.317030
iter  40 value 4834.300732
iter  50 value 4691.782340
iter  60 value 4670.057028
iter  70 value 4637.327352
iter  80 value 4585.360931
iter  90 value 4572.765127
iter 100 value 4547.513458
final  value 4547.513458 
stopped after 100 iterations
                           Df      AIC
- log_pop22                50 9197.460
- thr_temp                 50 9198.280
- thr_prec                 50 9198.459
&lt;none&gt;                     52 9199.772
- prop_esgot               50 9201.411
- pop22                    50 9202.289
+ +thr_umid                54 9202.576
+ +prop_residuo            54 9202.858
- bioma                    42 9203.002
+ +pop_residuo_interaction 54 9203.027
+ +tipo_regiao             54 9203.518
+ +pop_esgot_interaction   54 9203.716
- precip_tot               50 9203.858
- temp_precip_interaction  50 9205.429
- thr_temp_umid            50 9215.316
- altitude                 50 9217.956
- temp_umid_interaction    50 9241.898
- temp_med                 50 9251.082
- umid_med                 50 9251.656
- koppen                   36 9259.249
# weights:  78 (50 variable)
initial  value 6119.270448 
iter  10 value 4865.890190
iter  20 value 4780.973634
iter  30 value 4660.299549
iter  40 value 4585.701537
iter  50 value 4567.140064
iter  60 value 4549.028913
final  value 4548.729988 
converged

Step:  AIC=9197.46
Transition ~ temp_med + umid_med + precip_tot + thr_temp + thr_prec + 
    thr_temp_umid + altitude + bioma + koppen + pop22 + prop_esgot + 
    temp_umid_interaction + temp_precip_interaction

trying - temp_med 
# weights:  75 (48 variable)
initial  value 6119.270448 
iter  10 value 4865.850666
iter  20 value 4785.070392
iter  30 value 4651.731914
iter  40 value 4582.204922
iter  50 value 4577.058107
iter  60 value 4576.960654
final  value 4576.959887 
converged
trying - umid_med 
# weights:  75 (48 variable)
initial  value 6119.270448 
iter  10 value 4865.911715
iter  20 value 4792.867693
iter  30 value 4625.073407
iter  40 value 4580.731427
iter  50 value 4577.150645
iter  60 value 4577.052499
final  value 4577.051820 
converged
trying - precip_tot 
# weights:  75 (48 variable)
initial  value 6119.270448 
iter  10 value 4870.551703
iter  20 value 4792.585535
iter  30 value 4649.795033
iter  40 value 4583.343513
iter  50 value 4558.376400
iter  60 value 4552.707714
final  value 4552.639372 
converged
trying - thr_temp 
# weights:  75 (48 variable)
initial  value 6119.270448 
iter  10 value 4850.784833
iter  20 value 4781.935648
iter  30 value 4637.141429
iter  40 value 4584.117085
iter  50 value 4563.081621
iter  60 value 4550.048673
final  value 4550.013114 
converged
trying - thr_prec 
# weights:  75 (48 variable)
initial  value 6119.270448 
iter  10 value 4865.944332
iter  20 value 4781.094396
iter  30 value 4676.157353
iter  40 value 4587.557266
iter  50 value 4556.838762
iter  60 value 4550.095033
final  value 4550.038357 
converged
trying - thr_temp_umid 
# weights:  75 (48 variable)
initial  value 6119.270448 
iter  10 value 4884.490336
iter  20 value 4782.476652
iter  30 value 4627.511110
iter  40 value 4582.964171
iter  50 value 4561.718631
iter  60 value 4558.794933
final  value 4558.792438 
converged
trying - altitude 
# weights:  75 (48 variable)
initial  value 6119.270448 
iter  10 value 4849.806758
iter  20 value 4763.553956
iter  30 value 4628.262179
iter  40 value 4590.473046
iter  50 value 4567.080663
iter  60 value 4559.900931
final  value 4559.885184 
converged
trying - bioma 
# weights:  63 (40 variable)
initial  value 6119.270448 
iter  10 value 4865.891349
iter  20 value 4785.421237
iter  30 value 4642.260693
iter  40 value 4590.973606
iter  50 value 4561.507872
final  value 4560.378106 
converged
trying - koppen 
# weights:  54 (34 variable)
initial  value 6119.270448 
iter  10 value 4865.895377
iter  20 value 4807.796284
iter  30 value 4677.092557
iter  40 value 4596.340009
iter  50 value 4594.874265
iter  50 value 4594.874261
iter  50 value 4594.874261
final  value 4594.874261 
converged
trying - pop22 
# weights:  75 (48 variable)
initial  value 6119.270448 
iter  10 value 5440.117482
iter  20 value 5287.589281
iter  30 value 4854.255310
iter  40 value 4615.234649
iter  50 value 4580.336050
iter  60 value 4558.881759
final  value 4558.010368 
converged
trying - prop_esgot 
# weights:  75 (48 variable)
initial  value 6119.270448 
iter  10 value 4867.475761
iter  20 value 4766.120645
iter  30 value 4629.509618
iter  40 value 4585.612227
iter  50 value 4559.588555
iter  60 value 4552.222409
final  value 4552.164281 
converged
trying - temp_umid_interaction 
# weights:  75 (48 variable)
initial  value 6119.270448 
iter  10 value 4916.680995
iter  20 value 4865.620236
iter  30 value 4638.823453
iter  40 value 4581.242864
iter  50 value 4572.450621
iter  60 value 4572.354894
final  value 4572.352190 
converged
trying - temp_precip_interaction 
# weights:  75 (48 variable)
initial  value 6119.270448 
iter  10 value 5141.064360
iter  20 value 4997.711420
iter  30 value 4624.417152
iter  40 value 4584.183331
iter  50 value 4565.475273
iter  60 value 4553.659543
final  value 4553.444550 
converged
trying + thr_umid 
# weights:  81 (52 variable)
initial  value 6119.270448 
iter  10 value 4871.896002
iter  20 value 4811.412420
iter  30 value 4668.562612
iter  40 value 4585.605661
iter  50 value 4574.790137
iter  60 value 4548.884369
final  value 4548.143895 
converged
trying + tipo_regiao 
# weights:  81 (52 variable)
initial  value 6119.270448 
iter  10 value 4865.889930
iter  20 value 4780.469379
iter  30 value 4661.442848
iter  40 value 4586.107105
iter  50 value 4575.787340
iter  60 value 4549.329343
final  value 4548.577859 
converged
trying + prop_residuo 
# weights:  81 (52 variable)
initial  value 6119.270448 
iter  10 value 4862.878463
iter  20 value 4812.358066
iter  30 value 4676.575519
iter  40 value 4595.150746
iter  50 value 4575.244583
iter  60 value 4549.159488
final  value 4548.372741 
converged
trying + pop_esgot_interaction 
# weights:  81 (52 variable)
initial  value 6119.270448 
iter  10 value 5113.416479
iter  20 value 4967.781021
iter  30 value 4790.563840
iter  40 value 4700.097865
iter  50 value 4608.971077
iter  60 value 4604.395967
iter  70 value 4592.196804
iter  80 value 4579.463009
iter  90 value 4576.810189
iter  90 value 4576.810189
iter 100 value 4574.999839
final  value 4574.999839 
stopped after 100 iterations
trying + pop_residuo_interaction 
# weights:  81 (52 variable)
initial  value 6119.270448 
iter  10 value 5099.331305
iter  20 value 5014.648436
iter  30 value 4789.402555
iter  40 value 4631.046281
iter  50 value 4575.016308
iter  60 value 4548.655916
final  value 4547.782127 
converged
trying + log_pop22 
# weights:  81 (52 variable)
initial  value 6119.270448 
iter  10 value 4865.893478
iter  20 value 4796.520676
iter  30 value 4724.124154
iter  40 value 4602.516674
iter  50 value 4573.944135
iter  60 value 4548.628382
final  value 4547.885929 
converged
                           Df      AIC
- thr_temp                 48 9196.026
- thr_prec                 48 9196.077
&lt;none&gt;                     50 9197.460
+ +pop_residuo_interaction 52 9199.564
+ +log_pop22               52 9199.772
+ +thr_umid                52 9200.288
- prop_esgot               48 9200.329
+ +prop_residuo            52 9200.745
- bioma                    40 9200.756
+ +tipo_regiao             52 9201.156
- precip_tot               48 9201.279
- temp_precip_interaction  48 9202.889
- pop22                    48 9212.021
- thr_temp_umid            48 9213.585
- altitude                 48 9215.770
- temp_umid_interaction    48 9240.704
- temp_med                 48 9249.920
- umid_med                 48 9250.104
+ +pop_esgot_interaction   52 9254.000
- koppen                   34 9257.749
# weights:  75 (48 variable)
initial  value 6119.270448 
iter  10 value 4850.784833
iter  20 value 4781.935648
iter  30 value 4637.141429
iter  40 value 4584.117085
iter  50 value 4563.081621
iter  60 value 4550.048673
final  value 4550.013114 
converged

Step:  AIC=9196.03
Transition ~ temp_med + umid_med + precip_tot + thr_prec + thr_temp_umid + 
    altitude + bioma + koppen + pop22 + prop_esgot + temp_umid_interaction + 
    temp_precip_interaction

trying - temp_med 
# weights:  72 (46 variable)
initial  value 6119.270448 
iter  10 value 4850.755402
iter  20 value 4775.374375
iter  30 value 4620.329950
iter  40 value 4580.100943
iter  50 value 4577.224857
iter  60 value 4577.144934
final  value 4577.144641 
converged
trying - umid_med 
# weights:  72 (46 variable)
initial  value 6119.270448 
iter  10 value 4851.030037
iter  20 value 4795.379296
iter  30 value 4624.213329
iter  40 value 4581.467372
iter  50 value 4577.956455
iter  60 value 4577.871621
final  value 4577.870823 
converged
trying - precip_tot 
# weights:  72 (46 variable)
initial  value 6119.270448 
iter  10 value 4841.363076
iter  20 value 4775.952807
iter  30 value 4619.613179
iter  40 value 4581.776092
iter  50 value 4555.489877
iter  60 value 4553.342892
final  value 4553.342769 
converged
trying - thr_prec 
# weights:  72 (46 variable)
initial  value 6119.270448 
iter  10 value 4850.852305
iter  20 value 4776.160500
iter  30 value 4653.946606
iter  40 value 4584.768955
iter  50 value 4553.936334
iter  60 value 4551.501858
final  value 4551.501684 
converged
trying - thr_temp_umid 
# weights:  72 (46 variable)
initial  value 6119.270448 
iter  10 value 4863.467811
iter  20 value 4775.272505
iter  30 value 4634.610373
iter  40 value 4580.859039
iter  50 value 4560.066247
iter  60 value 4559.531858
iter  60 value 4559.531834
iter  60 value 4559.531834
final  value 4559.531834 
converged
trying - altitude 
# weights:  72 (46 variable)
initial  value 6119.270448 
iter  10 value 4854.969651
iter  20 value 4760.099361
iter  30 value 4616.354828
iter  40 value 4589.315573
iter  50 value 4563.103598
iter  60 value 4560.945174
iter  60 value 4560.945145
iter  60 value 4560.945145
final  value 4560.945145 
converged
trying - bioma 
# weights:  60 (38 variable)
initial  value 6119.270448 
iter  10 value 4850.786392
iter  20 value 4785.490525
iter  30 value 4635.944800
iter  40 value 4589.411378
iter  50 value 4562.470458
final  value 4561.562238 
converged
trying - koppen 
# weights:  51 (32 variable)
initial  value 6119.270448 
iter  10 value 4850.791000
iter  20 value 4811.705605
iter  30 value 4666.445640
iter  40 value 4605.468302
iter  50 value 4604.184332
iter  50 value 4604.184315
iter  50 value 4604.184315
final  value 4604.184315 
converged
trying - pop22 
# weights:  72 (46 variable)
initial  value 6119.270448 
iter  10 value 5411.086137
iter  20 value 5173.122515
iter  30 value 4746.491873
iter  40 value 4605.436191
iter  50 value 4568.995635
iter  60 value 4559.699963
final  value 4559.389012 
converged
trying - prop_esgot 
# weights:  72 (46 variable)
initial  value 6119.270448 
iter  10 value 4852.679210
iter  20 value 4783.448347
iter  30 value 4618.393824
iter  40 value 4584.317199
iter  50 value 4555.690857
iter  60 value 4553.378811
final  value 4553.378754 
converged
trying - temp_umid_interaction 
# weights:  72 (46 variable)
initial  value 6119.270448 
iter  10 value 4926.085813
iter  20 value 4823.140730
iter  30 value 4625.618777
iter  40 value 4578.472007
iter  50 value 4572.613005
iter  60 value 4572.544971
final  value 4572.543235 
converged
trying - temp_precip_interaction 
# weights:  72 (46 variable)
initial  value 6119.270448 
iter  10 value 5089.614750
iter  20 value 4960.186656
iter  30 value 4617.154465
iter  40 value 4584.503712
iter  50 value 4556.219343
iter  60 value 4554.064190
iter  60 value 4554.064171
iter  60 value 4554.064171
final  value 4554.064171 
converged
trying + thr_temp 
# weights:  78 (50 variable)
initial  value 6119.270448 
iter  10 value 4865.890190
iter  20 value 4780.973457
iter  30 value 4660.298591
iter  40 value 4585.691969
iter  50 value 4567.131777
iter  60 value 4549.028783
final  value 4548.729988 
converged
trying + thr_umid 
# weights:  78 (50 variable)
initial  value 6119.270448 
iter  10 value 4853.502204
iter  20 value 4802.655566
iter  30 value 4664.792197
iter  40 value 4586.250854
iter  50 value 4574.265824
iter  60 value 4549.337104
final  value 4548.782731 
converged
trying + tipo_regiao 
# weights:  78 (50 variable)
initial  value 6119.270448 
iter  10 value 4850.784525
iter  20 value 4781.572824
iter  30 value 4638.745821
iter  40 value 4584.745532
iter  50 value 4572.339672
iter  60 value 4550.300108
final  value 4549.875589 
converged
trying + prop_residuo 
# weights:  78 (50 variable)
initial  value 6119.270448 
iter  10 value 4847.451534
iter  20 value 4805.921998
iter  30 value 4686.971082
iter  40 value 4587.353423
iter  50 value 4571.114853
iter  60 value 4550.171609
final  value 4549.644839 
converged
trying + pop_esgot_interaction 
# weights:  78 (50 variable)
initial  value 6119.270448 
iter  10 value 5122.693243
iter  20 value 4965.731849
iter  30 value 4743.129860
iter  40 value 4590.925907
iter  50 value 4575.872935
iter  60 value 4550.902235
final  value 4550.006714 
converged
trying + pop_residuo_interaction 
# weights:  78 (50 variable)
initial  value 6119.270448 
iter  10 value 5108.048292
iter  20 value 5011.268954
iter  30 value 4951.772847
iter  40 value 4667.240656
iter  50 value 4653.292615
iter  60 value 4597.923188
iter  70 value 4580.516351
iter  80 value 4554.814367
iter  90 value 4548.999648
final  value 4548.977838 
converged
trying + log_pop22 
# weights:  78 (50 variable)
initial  value 6119.270448 
iter  10 value 4850.786667
iter  20 value 4774.862909
iter  30 value 4663.482147
iter  40 value 4583.240011
iter  50 value 4569.006886
iter  60 value 4549.511056
final  value 4549.140058 
converged
                           Df      AIC
- thr_prec                 46 9195.003
&lt;none&gt;                     48 9196.026
+ +thr_temp                50 9197.460
+ +thr_umid                50 9197.565
+ +pop_residuo_interaction 50 9197.956
+ +log_pop22               50 9198.280
- precip_tot               46 9198.686
- prop_esgot               46 9198.758
- bioma                    38 9199.124
+ +prop_residuo            50 9199.290
+ +tipo_regiao             50 9199.751
+ +pop_esgot_interaction   50 9200.013
- temp_precip_interaction  46 9200.128
- pop22                    46 9210.778
- thr_temp_umid            46 9211.064
- altitude                 46 9213.890
- temp_umid_interaction    46 9237.086
- temp_med                 46 9246.289
- umid_med                 46 9247.742
- koppen                   32 9272.369
# weights:  72 (46 variable)
initial  value 6119.270448 
iter  10 value 4850.852305
iter  20 value 4776.160500
iter  30 value 4653.946606
iter  40 value 4584.768955
iter  50 value 4553.936334
iter  60 value 4551.501858
final  value 4551.501684 
converged

Step:  AIC=9195
Transition ~ temp_med + umid_med + precip_tot + thr_temp_umid + 
    altitude + bioma + koppen + pop22 + prop_esgot + temp_umid_interaction + 
    temp_precip_interaction

trying - temp_med 
# weights:  69 (44 variable)
initial  value 6119.270448 
iter  10 value 4850.822873
iter  20 value 4761.222395
iter  30 value 4605.508922
iter  40 value 4582.929875
iter  50 value 4581.392547
final  value 4581.357763 
converged
trying - umid_med 
# weights:  69 (44 variable)
initial  value 6119.270448 
iter  10 value 4851.098985
iter  20 value 4788.461655
iter  30 value 4612.609885
iter  40 value 4583.583033
iter  50 value 4582.105388
iter  60 value 4582.065707
final  value 4582.065571 
converged
trying - precip_tot 
# weights:  69 (44 variable)
initial  value 6119.270448 
iter  10 value 4841.572580
iter  20 value 4745.800136
iter  30 value 4615.367491
iter  40 value 4585.562152
iter  50 value 4555.878698
final  value 4554.905914 
converged
trying - thr_temp_umid 
# weights:  69 (44 variable)
initial  value 6119.270448 
iter  10 value 4863.371852
iter  20 value 4755.009198
iter  30 value 4617.343268
iter  40 value 4583.532428
iter  50 value 4563.275658
final  value 4562.878678 
converged
trying - altitude 
# weights:  69 (44 variable)
initial  value 6119.270448 
iter  10 value 4855.155268
iter  20 value 4746.625154
iter  30 value 4616.641404
iter  40 value 4598.078576
iter  50 value 4567.494463
iter  60 value 4565.698845
final  value 4565.698543 
converged
trying - bioma 
# weights:  57 (36 variable)
initial  value 6119.270448 
iter  10 value 4850.853867
iter  20 value 4779.729168
iter  30 value 4616.655107
iter  40 value 4587.604847
iter  50 value 4563.608729
final  value 4563.183933 
converged
trying - koppen 
# weights:  48 (30 variable)
initial  value 6119.270448 
iter  10 value 4850.858479
iter  20 value 4802.184350
iter  30 value 4645.568194
iter  40 value 4605.338916
final  value 4604.627974 
converged
trying - pop22 
# weights:  69 (44 variable)
initial  value 6119.270448 
iter  10 value 5411.237269
iter  20 value 5186.142417
iter  30 value 4730.277010
iter  40 value 4596.275531
iter  50 value 4563.923042
iter  60 value 4560.914731
final  value 4560.897396 
converged
trying - prop_esgot 
# weights:  69 (44 variable)
initial  value 6119.270448 
iter  10 value 4852.749610
iter  20 value 4763.640618
iter  30 value 4614.619922
iter  40 value 4585.203351
iter  50 value 4556.218984
final  value 4554.933328 
converged
trying - temp_umid_interaction 
# weights:  69 (44 variable)
initial  value 6119.270448 
iter  10 value 4926.109346
iter  20 value 4802.330451
iter  30 value 4603.568666
iter  40 value 4579.710539
iter  50 value 4577.013728
iter  60 value 4576.968494
final  value 4576.968399 
converged
trying - temp_precip_interaction 
# weights:  69 (44 variable)
initial  value 6119.270448 
iter  10 value 5089.727670
iter  20 value 4908.492882
iter  30 value 4624.752028
iter  40 value 4589.055103
iter  50 value 4557.005980
final  value 4556.041654 
converged
trying + thr_temp 
# weights:  75 (48 variable)
initial  value 6119.270448 
iter  10 value 4865.944332
iter  20 value 4781.094688
iter  30 value 4676.195004
iter  40 value 4587.551228
iter  50 value 4556.847020
iter  60 value 4550.094952
final  value 4550.038357 
converged
trying + thr_umid 
# weights:  75 (48 variable)
initial  value 6119.270448 
iter  10 value 4853.552185
iter  20 value 4785.236108
iter  30 value 4652.505989
iter  40 value 4587.339338
iter  50 value 4557.593561
iter  60 value 4550.175947
final  value 4550.123631 
converged
trying + thr_prec 
# weights:  75 (48 variable)
initial  value 6119.270448 
iter  10 value 4850.784833
iter  20 value 4781.935045
iter  30 value 4637.141867
iter  40 value 4584.114540
iter  50 value 4563.085559
iter  60 value 4550.048591
final  value 4550.013114 
converged
trying + tipo_regiao 
# weights:  75 (48 variable)
initial  value 6119.270448 
iter  10 value 4850.851997
iter  20 value 4775.732415
iter  30 value 4618.882037
iter  40 value 4585.600249
iter  50 value 4564.777657
iter  60 value 4551.445587
final  value 4551.340486 
converged
trying + prop_residuo 
# weights:  75 (48 variable)
initial  value 6119.270448 
iter  10 value 4847.514725
iter  20 value 4792.396102
iter  30 value 4651.504263
iter  40 value 4587.168841
iter  50 value 4565.790673
iter  60 value 4551.390123
final  value 4551.299043 
converged
trying + pop_esgot_interaction 
# weights:  75 (48 variable)
initial  value 6119.270448 
iter  10 value 5122.724278
iter  20 value 4963.412235
iter  30 value 4783.908351
iter  40 value 4680.783982
iter  50 value 4637.944458
iter  60 value 4610.955268
iter  70 value 4595.755240
iter  80 value 4592.882622
iter  90 value 4588.608121
iter 100 value 4588.064460
final  value 4588.064460 
stopped after 100 iterations
trying + pop_residuo_interaction 
# weights:  75 (48 variable)
initial  value 6119.270448 
iter  10 value 5108.068080
iter  20 value 5008.003560
iter  30 value 4788.988290
iter  40 value 4628.216329
iter  50 value 4573.244772
iter  60 value 4551.215841
final  value 4550.592070 
converged
trying + log_pop22 
# weights:  75 (48 variable)
initial  value 6119.270448 
iter  10 value 4850.854129
iter  20 value 4779.684604
iter  30 value 4648.817262
iter  40 value 4587.258570
iter  50 value 4564.995284
iter  60 value 4550.717115
final  value 4550.667632 
converged
                           Df      AIC
&lt;none&gt;                     46 9195.003
+ +thr_prec                48 9196.026
+ +thr_temp                48 9196.077
+ +thr_umid                48 9196.247
+ +pop_residuo_interaction 48 9197.184
+ +log_pop22               48 9197.335
- precip_tot               44 9197.812
- prop_esgot               44 9197.867
- bioma                    36 9198.368
+ +prop_residuo            48 9198.598
+ +tipo_regiao             48 9198.681
- temp_precip_interaction  44 9200.083
- pop22                    44 9209.795
- thr_temp_umid            44 9213.757
- altitude                 44 9219.397
- temp_umid_interaction    44 9241.937
- temp_med                 44 9250.716
- umid_med                 44 9252.131
- koppen                   30 9269.256
+ +pop_esgot_interaction   48 9272.129</code></pre>
</div>
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(step_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
multinom(formula = Transition ~ temp_med + umid_med + precip_tot + 
    thr_temp_umid + altitude + bioma + koppen + pop22 + prop_esgot + 
    temp_umid_interaction + temp_precip_interaction, data = data)

Coefficients:
         (Intercept)  temp_med   umid_med   precip_tot thr_temp_umid
Melhorou   -46.43815  1.860428  0.6642842 -0.009047267   0.009827222
Piorou      32.28161 -1.227861 -0.3781523  0.004664138  -0.003668601
              altitude biomacaatinga biomacerrado biomamata atlantica
Melhorou -0.0005521101    0.05494592   -0.2296275          -0.1211043
Piorou   -0.0014094726   -0.70150934   -0.5939829          -0.8096036
          biomapampa biomapantanal   koppenAm   koppenAs    koppenAw  koppenBSh
Melhorou -0.03443726    -8.2398682 -0.6606228 -0.2386505 -0.09157772 -0.4529037
Piorou   -1.36902684    -0.5842715 -0.7821338 -0.7240518 -0.83791989 -0.9631628
          koppenCfa  koppenCfb   koppenCwa  koppenCwb         pop22
Melhorou -1.0384022  0.1235853  0.05201358  0.9070849 -3.137423e-06
Piorou   -0.6724688 -0.8693434 -1.30640800 -1.4684384 -3.224179e-07
           prop_esgot temp_umid_interaction temp_precip_interaction
Melhorou -0.003257302           -0.02887121            0.0004164665
Piorou    0.002325281            0.01520146           -0.0002205516

Std. Errors:
          (Intercept)     temp_med     umid_med   precip_tot thr_temp_umid
Melhorou 1.395977e-06 7.306159e-05 0.0001654453 0.0011212322  0.0009745281
Piorou   1.248594e-06 6.503347e-05 0.0001272013 0.0008619562  0.0010191997
             altitude biomacaatinga biomacerrado biomamata atlantica
Melhorou 0.0001808213  4.247305e-06 4.948287e-06        9.093524e-06
Piorou   0.0001375611  2.854525e-06 3.776440e-06        6.493777e-06
           biomapampa biomapantanal     koppenAm     koppenAs     koppenAw
Melhorou 5.694856e-07  3.349372e-11 1.171370e-06 3.845187e-06 7.400885e-06
Piorou   8.787364e-07  1.157066e-07 7.385019e-07 2.378395e-06 5.328651e-06
            koppenBSh    koppenCfa    koppenCfb    koppenCwa    koppenCwb
Melhorou 1.159225e-06 2.705636e-06 4.325524e-06 3.515259e-06 1.420953e-06
Piorou   8.563030e-07 2.913643e-06 1.736650e-06 2.540344e-06 8.698928e-07
                pop22  prop_esgot temp_umid_interaction temp_precip_interaction
Melhorou 9.715192e-07 0.001654927          0.0001916610            4.654913e-05
Piorou   2.900268e-07 0.001183321          0.0001905889            3.767216e-05

Residual Deviance: 9103.003 
AIC: 9195.003 </code></pre>
</div>
</div>
<section id="matriz-de-confusão-do-stepwise-1" class="level3">
<h3 class="anchored" data-anchor-id="matriz-de-confusão-do-stepwise-1">6.1 Matriz de confusão do stepwise</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="co"># previsões</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>previsoes <span class="ot">&lt;-</span> <span class="fu">predict</span>(step_model, <span class="at">newdata =</span> data)</span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a><span class="co"># matriz de confusão </span></span>
<span id="cb73-5"><a href="#cb73-5" aria-hidden="true" tabindex="-1"></a>matriz_confusao <span class="ot">&lt;-</span> <span class="fu">confusionMatrix</span>(previsoes, data<span class="sc">$</span>Transition)</span>
<span id="cb73-6"><a href="#cb73-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(matriz_confusao)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

            Reference
Prediction   Se manteve Melhorou Piorou
  Se manteve       3564      752   1085
  Melhorou            0        0      0
  Piorou             84        7     78

Overall Statistics
                                          
               Accuracy : 0.6539          
                 95% CI : (0.6412, 0.6664)
    No Information Rate : 0.6549          
    P-Value [Acc &gt; NIR] : 0.5732          
                                          
                  Kappa : 0.0347          
                                          
 Mcnemar's Test P-Value : &lt;2e-16          

Statistics by Class:

                     Class: Se manteve Class: Melhorou Class: Piorou
Sensitivity                    0.97697          0.0000       0.06707
Specificity                    0.04422          1.0000       0.97935
Pos Pred Value                 0.65988             NaN       0.46154
Neg Pred Value                 0.50296          0.8637       0.79911
Prevalence                     0.65494          0.1363       0.20880
Detection Rate                 0.63986          0.0000       0.01400
Detection Prevalence           0.96966          0.0000       0.03034
Balanced Accuracy              0.51060          0.5000       0.52321</code></pre>
</div>
</div>
</section>
</section>
<section id="análise-de-resíduos-1" class="level2">
<h2 class="anchored" data-anchor-id="análise-de-resíduos-1">7. Análise de resíduos</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Resíduos deviance</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>residuals_deviance <span class="ot">&lt;-</span> <span class="fu">residuals</span>(step_model, <span class="at">type =</span> <span class="st">"deviance"</span>)</span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(residuals_deviance, <span class="at">main =</span> <span class="st">"Resíduos Deviance"</span>, <span class="at">ylab =</span> <span class="st">"Resíduos"</span>, <span class="at">xlab =</span> <span class="st">"Observações"</span>)</span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">0</span>, <span class="at">col =</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analise_regressao_multinomial_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="do">### OUTRO</span></span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular os resíduos deviance</span></span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a>residuals_deviance <span class="ot">&lt;-</span> <span class="fu">residuals</span>(step_model, <span class="at">type =</span> <span class="st">"deviance"</span>)</span>
<span id="cb76-5"><a href="#cb76-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-6"><a href="#cb76-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Função para gerar um QQ plot com envelope</span></span>
<span id="cb76-7"><a href="#cb76-7" aria-hidden="true" tabindex="-1"></a><span class="fu">qqPlot</span>(residuals_deviance, </span>
<span id="cb76-8"><a href="#cb76-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">main =</span> <span class="st">"QQ Plot dos Resíduos com Envelope de Confiança"</span>,</span>
<span id="cb76-9"><a href="#cb76-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">xlab =</span> <span class="st">"Quantis Teóricos"</span>,</span>
<span id="cb76-10"><a href="#cb76-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">ylab =</span> <span class="st">"Resíduos"</span>,</span>
<span id="cb76-11"><a href="#cb76-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">id =</span> <span class="cn">FALSE</span>, <span class="co"># Desativar a identificação de pontos</span></span>
<span id="cb76-12"><a href="#cb76-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">envelope =</span> <span class="fl">0.95</span>) <span class="co"># Adicionar envelope de confiança de 95%</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analise_regressao_multinomial_files/figure-html/unnamed-chunk-21-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>REAMOSTRAGEM?</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>