---
title: "Determinantes"
author: "Iasmim, Raquel, Eduardo e Claudia"
format: pdf
editor: visual
editor_options: 
  chunk_output_type: console
---

#Bibliotecas

```{r}
#chooseCRANmirror()
#install.packages('tinytex')
library(tinytex)
library(dplyr)
library(ggpubr)
library(ggplot2)
library(car)
library(MASS)
library(nnet) 
library(tidyr) # Para pivot_wider
```

#Bancos

```{r}

# 2010-2019


d_10_19 <- read.csv2("Dengue/dengue_pattern_10_19.csv")
det <- read.csv2("Determinantes/banco_determinantes_fim.csv", fileEncoding = "latin1")

d1 <- left_join(d_10_19, det, by = "muni_code" )
# NA
na_columns <- names(d1)[colSums(is.na(d1)) > 0]
print(na_columns)

# Transformar variáveis em fatores
factor_vars <- c("dengue_pattern", "tipo_regiao", "bioma", "koppen")

# Aplicar transformação para todas as variáveis em fator de uma vez
d1[factor_vars] <- lapply(d1[factor_vars], as.factor)

# Verificar se a transformação foi aplicada corretamente
#str(d1)


```

# Análise estatística 2010-2019

## Análise varivaies categoricas

### Medidas resumo

###Calculando bioma e Koppen somando 100% na linha

```{r}

# Função para criar tabela com valores absolutos e proporções na linha
create_summary_table <- function(variable, dengue_pattern){
  table_values <- table(variable, dengue_pattern)
  proportions <- prop.table(table_values, margin = 1) # Alterando para somar por linha
  
  # Combinando valores absolutos e proporções
  summary_table <- paste(table_values, "(", round(proportions * 100, 1), "%)", sep = "")
  summary_table <- matrix(summary_table, nrow = nrow(table_values), dimnames = dimnames(table_values))
  
  # Reformatando para a tabela final com categorias de dengue_pattern nas colunas
  summary_df <- as.data.frame(summary_table)
  summary_df$Variable <- rownames(summary_df)
  summary_df <- summary_df[, c("Variable", "Sem transmissão", "Episódico", "Episódico/Epidêmico", "Epidêmico", "Transmissão Persistente")]
  
  return(summary_df)
}

# Criando as tabelas para cada variável
bioma_summary <- create_summary_table(d1$bioma, d1$dengue_pattern)
koppen_summary <- create_summary_table(d1$koppen, d1$dengue_pattern)

# Exibindo as tabelas
bioma_summary
koppen_summary

# Salvando as tabelas em arquivos CSV
write.csv2(bioma_summary, "Determinantes/bioma_summary_10_19.csv", row.names = FALSE)
write.csv2(koppen_summary, "Determinantes/koppen_summary_10_19.csv", row.names = FALSE)

```

###Calculando Tipo de região somando 100% na coluna

```{r}
# Função para criar tabela com valores absolutos e proporções
create_summary_table <- function(variable, dengue_pattern){
  table_values <- table(variable, dengue_pattern)
  proportions <- prop.table(table_values, margin = 2)
  
  # Combinando valores absolutos e proporções
  summary_table <- paste(table_values, "(", round(proportions * 100, 1), "%)", sep = "")
  summary_table <- matrix(summary_table, nrow = nrow(table_values), dimnames = dimnames(table_values))
  
  # Reformatando para a tabela final com categorias de dengue_pattern na coluna
  summary_df <- as.data.frame(summary_table)
  summary_df$Variable <- rownames(summary_df)
  summary_df <- summary_df[, c("Variable", "Sem transmissão", "Episódico", "Episódico/Epidêmico", "Epidêmico", "Transmissão Persistente")]
  
  return(summary_df)
}

# Criando as tabelas para cada variável
tipo_regiao_summary <- create_summary_table(d1$tipo_regiao, d1$dengue_pattern)

# Salvando as tabelas em arquivos CSV
write.csv2(tipo_regiao_summary, "Determinantes/tipo_regiao_summary_10_19.csv", row.names = FALSE)
```

### Analise descritiva por gráficos Absoluto

```{r}
# Reordenar os níveis de dengue_pattern na ordem desejada
d1$dengue_pattern <- factor(d1$dengue_pattern, 
                            levels = c("Sem transmissão", "Episódico", "Episódico/Epidêmico", "Epidêmico", "Transmissão Persistente"))


# Plot 2: Gráfico de barras com destaque para tipo_regiao
ggplot(d1, aes(x = dengue_pattern, fill = tipo_regiao)) +
  geom_bar(position = position_dodge(width = 0.9), width = 0.7) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.1))) + 
  geom_text(stat='count', aes(label=..count..), vjust=-0.5, position = position_dodge(0.9)) +
  labs(title = "Distribuição do Padrão de Dengue por Região", x = "Padrão de Dengue", fill = "Região") +
  theme_minimal()

# Plot 3: Gráfico de barras com destaque para bioma
ggplot(d1, aes(x = dengue_pattern, fill = bioma)) +
  geom_bar(position = position_dodge(width = 0.9), width = 0.7) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.1))) + 
  geom_text(stat='count', aes(label=..count..), vjust=-0.5, position = position_dodge(0.9)) +
  labs(title = "Distribuição do Padrão de Dengue por Bioma", x = "Padrão de Dengue", fill = "Bioma") +
  theme_minimal()

# Plot 4: Gráfico de barras com destaque para classificação Koppen
ggplot(d1, aes(x = dengue_pattern, fill = koppen)) +
  geom_bar(position = position_dodge(width = 0.9), width = 0.7) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.1))) + 
  geom_text(stat='count', aes(label=..count..), vjust=-0.5, position = position_dodge(0.9)) +
  labs(title = "Distribuição do Padrão de Dengue por Classificação Köppen", x = "Padrão de Dengue", fill = "Classificação Köppen") +
  theme_minimal()

```

## Analise descritiva por gráficos proporção

```{r}
# Função para calcular as proporções
calculate_proportions <- function(variable, dengue_pattern){
  table_values <- table(dengue_pattern, variable)
  proportions <- prop.table(table_values, margin = 1)
  df <- as.data.frame(as.table(proportions))
  colnames(df) <- c("dengue_pattern", "variable", "proportion")
  return(df)
}

# Traduzindo os perfis de dengue_pattern para inglês
d1$dengue_pattern <- dplyr::recode(d1$dengue_pattern,
                                   "Sem transmissão" = "No transmission",
                                   "Episódico" = "Episodic",
                                   "Episódico/Epidêmico" = "Episodic/Epidemic",
                                   "Epidêmico" = "Epidemic",
                                   "Transmissão Persistente" = "Persistent transmission")

# Traduzindo a variável tipo_regiao para inglês
d1$tipo_regiao <- dplyr::recode(d1$tipo_regiao,
                                "metropolitana" = "Metropolitan",
                                "não metropolitana" = "Non-Metropolitan")

# Ordenando os perfis de dengue_pattern conforme desejado
dengue_order <- c("No transmission", "Episodic", "Episodic/Epidemic", "Epidemic", "Persistent transmission")

# Calculando proporções para cada variável
tipo_regiao_df <- calculate_proportions(d1$tipo_regiao, d1$dengue_pattern)
bioma_df <- calculate_proportions(d1$bioma, d1$dengue_pattern)
koppen_df <- calculate_proportions(d1$koppen, d1$dengue_pattern)

# Ordenando a variável dengue_pattern
tipo_regiao_df$dengue_pattern <- factor(tipo_regiao_df$dengue_pattern, levels = dengue_order)
bioma_df$dengue_pattern <- factor(bioma_df$dengue_pattern, levels = dengue_order)
koppen_df$dengue_pattern <- factor(koppen_df$dengue_pattern, levels = dengue_order)

# Função para exibir o rótulo condicionalmente
label_if_not_zero <- function(proportion) {
  ifelse(proportion > 0, scales::percent(proportion, accuracy = 0.1), "")
}

# Gráfico de barras para tipo_regiao sem linha de fundo
gg_tipo_regiao <- ggplot(tipo_regiao_df, aes(x = dengue_pattern, y = proportion, fill = variable)) +
  geom_bar(stat = "identity", position = "dodge", width = 0.3) +  # Aumentando a largura da barra
  geom_text(aes(label = label_if_not_zero(proportion)), 
            position = position_dodge(width = 0.3), vjust = -0.5, size = 3) +  # Aumentando o tamanho do texto
  scale_y_continuous(labels = scales::percent_format()) +
  labs(title = "Dengue Patterns by Region 2010-2019", 
       x = "Dengue Pattern", y = "Proportion", fill = "Region") +
  theme_minimal() +
  theme(panel.grid = element_blank(),    # Remove todas as linhas de grade
        panel.background = element_blank(),  # Remove o fundo do painel
        axis.line = element_blank())         # Remove as linhas dos eixos

# Salvando o gráfico
ggsave("figures/tipo_regiao_distribution_10_19.png", plot = gg_tipo_regiao, width = 10, height = 7)

# Gráfico de barras para bioma sem linha de fundo
gg_bioma <- ggplot(bioma_df, aes(x = dengue_pattern, y = proportion, fill = variable)) +
  geom_bar(stat = "identity", position = "dodge", width = 0.9) +  # Aumentando a largura da barra
  geom_text(aes(label = label_if_not_zero(proportion)), 
            position = position_dodge(width = 0.9), vjust = -0.5, size = 3) +  # Aumentando o tamanho do texto
  scale_y_continuous(labels = scales::percent_format()) +
  labs(title = "Dengue Patterns by Biome 2010-2019", 
       x = "Dengue Pattern", y = "Proportion", fill = "Biome") +
  theme_minimal() +
  theme(panel.grid = element_blank(),    # Remove todas as linhas de grade
        panel.background = element_blank(),  # Remove o fundo do painel
        axis.line = element_blank())         # Remove as linhas dos eixos

# Salvando o gráfico
ggsave("bioma_distribution.png", plot = gg_bioma, width = 10, height = 7)

# Gráfico de barras para koppen sem linha de fundo
gg_koppen <- ggplot(koppen_df, aes(x = dengue_pattern, y = proportion, fill = variable)) +
  geom_bar(stat = "identity", position = "dodge", width = 0.9) +  # Aumentando a largura da barra
  geom_text(aes(label = label_if_not_zero(proportion)), 
            position = position_dodge(width = 0.9), vjust = -0.5, size = 2) +  # Aumentando o tamanho do texto
  scale_y_continuous(labels = scales::percent_format()) +
  labs(title = "Proportional Distribution of Dengue Patterns by Köppen Classification", 
       x = "Dengue Pattern", y = "Proportion", fill = "Köppen") +
  theme_minimal() +
  theme(panel.grid = element_blank(),    # Remove todas as linhas de grade
        panel.background = element_blank(),  # Remove o fundo do painel
        axis.line = element_blank())         # Remove as linhas dos eixos

# Salvando o gráfico
ggsave("koppen_distribution.png", plot = gg_koppen, width = 10, height = 7)


```

### medidas de resumo das numericas

```{r}
# Função para calcular média e desvio padrão no formato desejado
calc_summary <- function(x) {
  paste0(round(mean(x, na.rm = TRUE), 2), " (", round(sd(x, na.rm = TRUE), 2), ")")
}

# Definindo a ordem dos níveis de dengue_pattern
d1 <- d1 %>%
  mutate(dengue_pattern = factor(dengue_pattern, 
                                 levels = c("Sem transmissão", 
                                            "Episódico", 
                                            "Episódico/Epidêmico", 
                                            "Epidêmico", 
                                            "Transmissão Persistente")))

# Gerar a tabela de resumo para as variáveis por 'dengue_pattern'
summary_table <- d1 %>%
  group_by(dengue_pattern) %>%
  summarise(
    Altitude = calc_summary(altitude),
    Prop_Esgot = calc_summary(prop_esgot),
    Prop_Abast = calc_summary(prop_abast),
    Prop_Residuo = calc_summary(prop_residuo),
    Populacao = calc_summary(pop22)
  ) %>%
  pivot_longer(cols = c(Altitude, Prop_Esgot, Prop_Abast, Prop_Residuo, Populacao), 
               names_to = "Variavel", 
               values_to = "Resumo") %>%
  pivot_wider(names_from = dengue_pattern, values_from = Resumo)

# Exibir a tabela
summary_table

write.csv2(summary_table, "Determinantes/numericas_summary.csv", row.names = FALSE)



```

# Análise 2020-2022
