---
title: "banco_det"
author: "Iasmim"
date: "2024-10-08"
output: html_document
editor_options: 
  chunk_output_type: console
---
Biblioteca
```{r}
setwd("~/GitHub/Epidynamics")
library(tidyr)
library(readr)
library(dplyr)

```

Bancos
```{r}
lixo <- read_csv2("Determinantes/lixo.csv", locale = locale(encoding = "Latin1"))
abastecimento_agua <- read_csv2("Determinantes/abastecimento agua.csv", locale = locale(encoding = "Latin1"))
instalações_sanitarias <- read_csv2("Determinantes/instalações sanitarias.csv", locale = locale(encoding = "Latin1"))
```

lixo
```{r}
# Separar a coluna em duas: número e nome
d1 <- lixo %>% 
  separate(code_muni, into = c("numero", "nome"), sep = " ", extra = "merge")

# Exibir o resultado
print(d1)
names(d1)

# Renomear as colunas 'numero' e 'nome' para 'code_muni' e 'munname'
d1 <- d1 %>%
  rename(code_muni = numero, munname = nome)

# Substituir vírgulas por pontos na 4ª coluna antes de converter para numérico
d1[[4]] <- as.numeric(gsub(",", ".", d1[[4]]))

# Transformar a 3ª coluna em numérica
d1[[3]] <- as.numeric(as.character(d1[[3]]))

# Criar a nova coluna 'prop_residuo' como a soma das colunas 3 e 4
d1 <- d1 %>%
  mutate(prop_residuo = d1[[3]] + d1[[4]])

# Verificar se houve algum problema na conversão (NA gerados)
problemas_conversao <- sum(is.na(d1[[3]])) + sum(is.na(d1[[4]]))

# Exibir se houve problemas de conversão
print(paste("Total de valores convertidos em NA: ", problemas_conversao))

# Excluir as colunas 3 e 4 do dataframe d1
d1_sem_colunas <- d1[, -c(3, 4)]

# Salvar o novo dataframe em um arquivo CSV
write.csv2(d1_sem_colunas, "Determinantes/lixo_certo.csv", row.names = FALSE)


```

abastecimento de agua
```{r}
# Separar a coluna em duas: número e nome
d2 <- abastecimento_agua %>% 
  separate(code_muni, into = c("numero", "nome"), sep = " ", extra = "merge")

# Exibir o resultado
print(d2)
names(d2)

# Renomear as colunas 'numero' e 'nome' para 'code_muni' e 'munname'
d2 <- d2 %>%
  rename(code_muni = numero, munname = nome)

# Substituir vírgulas por pontos na 4ª coluna antes de converter para numérico
d2[[4]] <- as.numeric(gsub(",", ".", d2[[4]]))

# Transformar a 3ª coluna em numérica
d2[[3]] <- as.numeric(as.character(d2[[3]]))

# Criar a nova coluna 'prop_residuo' como a soma das colunas 3 e 4
d2 <- d2 %>%
  mutate(prop_abast = d2[[3]] + d2[[4]])

# Verificar se houve algum problema na conversão (NA gerados)
problemas_conversao <- sum(is.na(d2[[3]])) + sum(is.na(d2[[4]]))

# Exibir se houve problemas de conversão
print(paste("Total de valores convertidos em NA: ", problemas_conversao))

# Excluir as colunas 3 e 4 do dataframe d1
d2_sem_colunas <- d2[, -c(3, 4)]

# Salvar o novo dataframe em um arquivo CSV
write.csv2(d2_sem_colunas, "Determinantes/abastecimento_agua_certo.csv", row.names = FALSE)

```

instalações sanitarias
```{r}
# Separar a coluna em duas: número e nome
d3 <- instalações_sanitarias %>% 
  separate(code_muni, into = c("numero", "nome"), sep = " ", extra = "merge")

# Exibir o resultado
print(d3)
names(d3)

# Renomear as colunas 'numero' e 'nome' para 'code_muni' e 'munname'
d3 <- d3 %>%
  rename(code_muni = numero, munname = nome)

# Substituir vírgulas por pontos na 4ª coluna antes de converter para numérico
d3[[4]] <- as.numeric(gsub(",", ".", d3[[4]]))

# Transformar a 3ª coluna em numérica
d3[[3]] <- as.numeric(as.character(d3[[3]]))

# Criar a nova coluna 'prop_abast' como a soma das colunas 3 e 4
d3 <- d3 %>%
  mutate(prop_esgot = d3[[3]] + d3[[4]])

# Verificar se houve algum problema na conversão (NA gerados)
problemas_conversao <- sum(is.na(d3[[3]])) + sum(is.na(d3[[4]]))

# Exibir se houve problemas de conversão
print(paste("Total de valores convertidos em NA: ", problemas_conversao))

# Excluir as colunas 3 e 4 do dataframe d3
d3_sem_colunas <- d3[, -c(3, 4)]

# Salvar o novo dataframe em um arquivo CSV
write.csv2(d3_sem_colunas, "Determinantes/instalações_certo.csv", row.names = FALSE)

```

## Juntando bancos de determinantes e ibge
```{r}
variaveis_IBGE <- read_csv2("Determinantes/variaveis_IBGE.csv")
banco_determinantes <- read_csv2("Determinantes/banco_determinantes.csv")

# Ajustar o muni_code no banco_determinantes removendo o último dígito para ter 6 dígitos
banco_determinantes <- banco_determinantes %>%
  mutate(muni_code_6 = substr(muni_code, 1, 6))

# Transformar a 3ª coluna em numérica
banco_determinantes [[10]] <- as.numeric(as.character(banco_determinantes [[10]]))

# Agora unir 
banco_final <- banco_determinantes %>%
  left_join(variaveis_IBGE, by = c("muni_code_6"))

# Remover a variável muni_code_6 e manter apenas muni_code com 7 dígitos no banco final
banco_final <- banco_final %>%
  select(-muni_code_6)

# Exibir o resultado final
print(banco_final)

# Salvar o novo dataframe em um arquivo CSV
write.csv2(banco_final, "Determinantes/banco_determinantes_fim.csv", row.names = FALSE)
```

